
/* Interior Studio 1.2 — style-neutral, scoped editing and physical light rig
 * One runtime; one active camera; one pointer owner; one render path.
 * Fixes the r164 transmission/depth-state feedback reproduced in ULTRA.
 * All coordinates in metres. No network, telemetry or external assets.
 */
(async function(C,T){'use strict';
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#webgl'),stage=$('#stage');
 C.templateHTML='<!doctype html>\n'+document.documentElement.outerHTML;
 if(window.PROJECT.customStyle){C.validateStyle(window.PROJECT.customStyle);const i=window.STYLE_CATALOG.styles.findIndex(x=>x.id===window.PROJECT.customStyle.id);if(i>=0)window.STYLE_CATALOG.styles[i]=window.PROJECT.customStyle;else window.STYLE_CATALOG.styles.push(window.PROJECT.customStyle);}
 await C.nativeAssets.prepare(window.PROJECT.nativeAssets||[]);
 const state=C.state={version:'html-skills/2.0.0',view:'overview',tool:'browse',tab:'walls',cut:false,roof:false,labels:false,doors:true,day:true,auto:false,ao:true,direct:false,quality:'live',wallLocked:true,wallVisible:true,furnitureVisible:true,exposure:.9,sun:2.35,azimuth:326,elevation:47,environment:.62,reflection:.65,lightPower:1,shadows:true,hdr:true,renderCount:0,errors:[],busy:false};
 let dirty=true,rendering=false,contextLost=false,selected=null,helper=null,gesture=null,lastTime=performance.now(),savedCameras=[],probeRT=null,probeOutput=null;
 const pointers=new Map(),history=[],redoHistory=[];
 function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(C.toastTimer);C.toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
 // Keep async export/probe transactions isolated from live edits and resize controls.
 function busy(message){state.busy=!!message;C.workspace?.cancel();if(C.workspace)C.workspace.lines.visible=!state.busy;C.lights?.suppress(state.busy);stage.inert=state.busy;$('#sidebar').inert=state.busy;$('#busy-overlay').hidden=!state.busy;if(message)$('#busy-message').textContent=message;}
 const paintPause=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 function fail(e){const text=e?.message||String(e);state.errors.push(text);console.error(e);toast('发生错误：'+text);}
 window.addEventListener('error',e=>state.errors.push(e.message));window.addEventListener('unhandledrejection',e=>state.errors.push(String(e.reason)));
 const R=C.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
 R.outputColorSpace=T.SRGBColorSpace;R.toneMapping=T.ACESFilmicToneMapping;R.toneMappingExposure=state.exposure;R.setClearColor('#d8d4cc');R.shadowMap.enabled=true;R.shadowMap.type=T.PCFSoftShadowMap;R.shadowMap.autoUpdate=false;R.autoClear=true;R.info.autoReset=false;
 const S=C.scene=new T.Scene();S.background=new T.Color('#d8d4cc');
 const root=C.root=new T.Group();root.name=window.PROJECT.name;S.add(root);
 $('#load-note').textContent='建立独立墙体、家具与编辑对象…';
 C.buildScene(root,window.PROJECT);
 let originalMeshes=0;root.traverse(o=>{if(o.isMesh)originalMeshes++;});
 // Safe glass settings: never combine a transmissive, DoubleSide, non-depth-writing
 // material in r164. Its back-face prepass can leave depth writes disabled before clear.
 const materials=new Set();root.traverse(o=>{if(o.isMesh)for(const m of(Array.isArray(o.material)?o.material:[o.material]))materials.add(m);});
 for(const m of materials){if(!m)continue;
  if(/玻璃/.test(m.name)&&m.isMeshPhysicalMaterial){m.transmission=0;m.transparent=true;m.opacity=.14;m.depthWrite=false;m.side=T.DoubleSide;m.roughness=.11;m.metalness=.03;}
  if(m.normalScale)m.normalScale.multiplyScalar(.45);
  if('envMapIntensity'in m)m.envMapIntensity=.75;
  if(/墙|涂料|哑光/.test(m.name)&&'roughness'in m)m.roughness=Math.max(.82,m.roughness);
 }
 C.optimizeLocal(root);root.visible=true;
 let walls=C.architecture.getObjectByName('完整墙体与洞口');C.walls=walls;
 let furnitureGroups=root.children.filter(o=>o!==C.architecture&&o!==C.ceiling);
 const ground=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({name:'摄影棚背景（不导出）',color:'#ded8ce',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.302;ground.receiveShadow=true;ground.userData.noExport=true;S.add(ground);
 const sun=new T.DirectionalLight('#fff4df',state.sun);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.1,far:40});sun.shadow.normalBias=.018;sun.shadow.bias=-.00012;S.add(sun,sun.target);
 const hemi=new T.HemisphereLight('#f5f3ef','#a89b86',.5);S.add(hemi);const fill=new T.DirectionalLight('#e8eff5',.28);fill.position.set(8,6,-5);S.add(fill);const ambient=new T.AmbientLight('#fff2de',.1);S.add(ambient);
 const styleDefaults=C.activeStyle.lighting;
 Object.assign(state,{exposure:styleDefaults.exposure,sun:styleDefaults.sun,environment:styleDefaults.environment,reflection:styleDefaults.reflection},window.PROJECT.lighting?.settings||{});
 const lightRig=C.lights=new C.LightRig(S,window.PROJECT.lighting?.lights||C.defaultLights(window.PROJECT,C.rooms,C.activeStyle),invalidate);

 // A modest, linear HDR environment. It is generated locally, not a photographic HDRI.
 const envData=new Float32Array(256*128*4);
 for(let y=0;y<128;y++)for(let x=0;x<256;x++){const u=x/255,v=y/127,k=.3+v*.28+2.0*Math.exp(-((u-.22)**2/.014+(v-.63)**2/.065))+1.2*Math.exp(-((u-.73)**2/.010+(v-.6)**2/.04));const i=(y*256+x)*4;envData[i]=k;envData[i+1]=k*.97;envData[i+2]=k*.91;envData[i+3]=1;}
 const eTex=new T.DataTexture(envData,256,128,T.RGBAFormat,T.FloatType);eTex.mapping=T.EquirectangularReflectionMapping;eTex.colorSpace=T.LinearSRGBColorSpace;eTex.needsUpdate=true;
 const pmrem=new T.PMREMGenerator(R),envRT=pmrem.fromEquirectangular(eTex);eTex.dispose();pmrem.dispose();S.environment=envRT.texture;
 const cam=C.camera=new T.PerspectiveCamera(38,1,.06,100),ortho=C.ortho=new T.OrthographicCamera(-9,9,7,-7,.1,65);ortho.up.set(0,0,-1);let active=cam;
 const controls=C.controls=new C.CameraControls(active,canvas);canvas.tabIndex=0;
 C.presets=C.previewPresets;
 const previewSelect=$('#quick-view');previewSelect.replaceChildren();const roomGrid=$('.room-grid');roomGrid.replaceChildren();
 Object.entries(C.presets).forEach(([id,p])=>{const option=document.createElement('option');option.value=id;option.textContent=p.title;previewSelect.append(option);if(!['overview','plan'].includes(id)){const button=document.createElement('button');button.dataset.view=id;button.textContent=p.title;roomGrid.append(button);}});
 $('#view-title').textContent=window.PROJECT.name;$('.brand h1').textContent=window.PROJECT.name.split(' · ')[0];

 // Half-float keeps highlights intact. The old unsigned-byte target clipped lighting
 // before tone mapping, flattening most materials towards the same white.
 const useHDR=R.extensions.has('EXT_color_buffer_float');
 const rt=new T.WebGLRenderTarget(16,16,{type:useHDR?T.HalfFloatType:T.UnsignedByteType,minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:true});rt.texture.colorSpace=T.LinearSRGBColorSpace;rt.depthTexture=new T.DepthTexture(16,16,T.UnsignedIntType);
 const postScene=new T.Scene(),postCam=new T.OrthographicCamera(-1,1,1,-1,0,1);
 const postMat=new T.ShaderMaterial({name:'线性 HDR → 接触遮蔽 → 色调映射',depthTest:false,depthWrite:false,uniforms:{tColor:{value:rt.texture},tDepth:{value:rt.depthTexture},invProj:{value:new T.Matrix4()},resolution:{value:new T.Vector2(16,16)},strength:{value:.48},radius:{value:.22}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`
  varying vec2 vUv;uniform sampler2D tColor,tDepth;uniform mat4 invProj;uniform vec2 resolution;uniform float strength,radius;
  vec3 point(vec2 uv){float d=texture2D(tDepth,uv).r;vec4 p=invProj*vec4(uv*2.-1.,d*2.-1.,1.);return p.xyz/p.w;}
  void main(){vec3 color=texture2D(tColor,vUv).rgb;float depth=texture2D(tDepth,vUv).r,oc=0.;
   if(depth<.9999&&strength>0.){vec3 P=point(vUv);vec3 N=normalize(cross(dFdx(P),dFdy(P)));float px=clamp(radius*resolution.y/max(1.,-P.z),2.,42.);
    for(int i=0;i<12;i++){float f=float(i)+.5,a=f*2.399963;vec2 uv=vUv+vec2(cos(a),sin(a))*sqrt(f/12.)*px/resolution;if(uv.x<0.||uv.x>1.||uv.y<0.||uv.y>1.)continue;vec3 D=point(uv)-P;float d=length(D);oc+=max(0.,dot(N,D/max(d,.0001))-.13)*(1.-smoothstep(.018,radius*1.8,d));}oc=clamp(oc/12.*strength*2.4,0.,.3);}
   gl_FragColor=vec4(color*(1.-oc),1.);
   #include <tonemapping_fragment>
   #include <colorspace_fragment>
  }`});postScene.add(new T.Mesh(new T.PlaneGeometry(2,2),postMat));
 state.direct=!useHDR;
 function invalidate(shadow=false){dirty=true;if(shadow)R.shadowMap.needsUpdate=true;}
 function safeClear(target){R.setRenderTarget(target);R.setScissorTest(false);R.state.buffers.depth.setTest(true);R.state.buffers.depth.setMask(true);R.state.buffers.color.setMask(true);R.clear(true,true,false);}
 function layout(ratio){const w=Math.max(1,stage.clientWidth),h=Math.max(1,stage.clientHeight);if(ratio!==undefined)R.setPixelRatio(ratio);R.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix();const extent=C.sceneBounds;const halfH=Math.max((extent.maxZ-extent.minZ)*.58,(extent.maxX-extent.minX)*.58/cam.aspect);ortho.left=-halfH*cam.aspect;ortho.right=halfH*cam.aspect;ortho.top=halfH;ortho.bottom=-halfH;ortho.updateProjectionMatrix();const b=new T.Vector2();R.getDrawingBufferSize(b);rt.setSize(b.x,b.y);postMat.uniforms.resolution.value.copy(b);invalidate();}
 C.layout=layout;
 function draw(){if(rendering||contextLost)return;rendering=true;try{syncLinkedLights();root.updateMatrixWorld(true);active.updateMatrixWorld(true);lightRig.scaleHandles(active,stage.clientHeight);if(helper&&selected)helper.setFromObject(selected.object);R.info.reset();
   if(state.direct){safeClear(null);R.render(S,active);}else{postMat.uniforms.invProj.value.copy(active.projectionMatrixInverse);postMat.uniforms.strength.value=state.ao?.48:0;safeClear(rt);R.render(S,active);safeClear(null);R.render(postScene,postCam);}
   state.renderCount++;dirty=false;updateLabels();C.workspace?.onFrame();$('#stats').textContent=`${(C.stats.triangles/1000).toFixed(0)}k 三角面 · ${R.info.render.calls} draw calls`;
  }catch(e){state.direct=true;invalidate();fail(e);}finally{R.setRenderTarget(null);R.state.buffers.depth.setMask(true);R.state.buffers.color.setMask(true);rendering=false;}}
 C.render=draw;
 function renderNow(){invalidate();draw();}
 function syncUI(){
  for(const [id,value]of Object.entries({'cut':state.cut,'roof':state.roof,'doors':state.doors,'labels-toggle':state.labels,'auto':state.auto,'wall-vis':state.wallVisible,'furniture-vis':state.furnitureVisible,'render-ao':state.ao,'render-direct':state.direct,'render-shadow':state.shadows,'hdr-env':state.hdr,'two-point':controls.twoPoint}))$("#"+id).checked=value;
  const lock=$('#wall-lock');lock.classList.toggle('active',state.wallLocked);lock.textContent=state.wallLocked?'🔒 已锁定':'🔓 可选择';
  $$('[data-view]').forEach(b=>b.classList.toggle('selected',state.view===b.dataset.view));if(C.presets[state.view])$('#quick-view').value=state.view;
  $('#view-title').textContent=C.presets[state.view]?.title||'自由机位';$('#view-en').textContent=active.isOrthographicCamera?'Orthographic / 俯视平移':controls.mode==='look'?'Look around / 相机原地转向':'Orbit / 固定中心环绕';$('#current-mode').textContent=state.cut?'剖切查看 · 模型本体未裁剪':'完整墙体 · '+(state.roof?'顶面显示':'顶面隐藏');
  $('#day').classList.toggle('selected',state.day);$('#night').classList.toggle('selected',!state.day);$('#camera-fov').value=cam.fov;output('camera-fov',cam.fov.toFixed(0)+'°');$('#camera-fov').disabled=active.isOrthographicCamera;
  $$('[data-nav]').forEach(b=>b.classList.toggle('selected',b.dataset.nav===controls.mode));
  $$('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===state.tool));
  $('#tool-hint').textContent={browse:'浏览模式：左键转视角，不会修改家具。',select:'单击选中完整家具；拖动转视角。',move:'左键拖动家具平移；右键只移动相机。',rotate:'左键拖动家具水平旋转；右键只移动相机。'}[state.tool];
  $('#undo').disabled=!history.length;$('#redo').disabled=!redoHistory.length;
  $('#quality-live').classList.toggle('active',state.quality==='live');$('#quality-photo').classList.toggle('active',state.quality==='photo');$('#hq-badge').classList.toggle('show',state.quality==='photo');
 }
 function output(id,value){const out=$('#'+id)?.parentElement.querySelector('output');if(out)out.textContent=value;}
 function setTab(id){if(!['style','walls','furniture','lights','sun','camera','render'].includes(id)||state.busy)return;cancelGesture();select(null);lightRig.select(null);state.tab=id;C.workspace?.cancel();state.tool=id==='furniture'?'move':'browse';state.auto=false;lightRig.show(id==='lights');$$('.pro-tab').forEach(b=>b.classList.toggle('selected',b.dataset.tab===id));$$('.pro-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===id));updateLightUI();syncUI();invalidate();}
 function setTool(tool){cancelGesture();state.tool=state.tab==='furniture'?tool:'browse';state.auto=false;syncUI();invalidate();}
 function applyBuilding(){walls.visible=state.wallVisible;C.ceiling.visible=state.roof;R.localClippingEnabled=state.cut;furnitureGroups.forEach(g=>g.visible=state.furnitureVisible);invalidate(true);}
 function setView(id){if(state.busy)return;const p=C.presets[id];if(!p)return;cancelGesture();state.auto=false;state.view=id;const outside=['overview','plan'].includes(id);state.cut=false;state.roof=!outside;state.labels=id==='plan';ground.visible=outside;
  active=id==='plan'?ortho:cam;controls.camera=active;controls.mode=outside?'orbit':'look';controls.twoPoint=false;
  cam.clearViewOffset();active.near=p.near||.04;active.position.fromArray(p.pos);controls.target.fromArray(p.target);if(active.isPerspectiveCamera){const fit=Math.max(1,(outside?1.10:.96)/Math.max(.35,cam.aspect));active.fov=Math.min(108,T.MathUtils.radToDeg(2*Math.atan(Math.tan(T.MathUtils.degToRad(p.fov/2))*fit)));}active.zoom=1;if(active.isPerspectiveCamera)cam.setViewOffset(cam.aspect,1,0,-(p.verticalShift||0)/2,cam.aspect,1);active.updateProjectionMatrix();controls.lookAt();applyBuilding();syncUI();invalidate(true);
  if(innerWidth<900)document.body.classList.remove('panel-open');}
 C.setView=setView;C.getActiveCamera=()=>active;
 function lighting(){const az=T.MathUtils.degToRad(state.azimuth),el=T.MathUtils.degToRad(state.elevation),r=14;sun.position.set(Math.sin(az)*Math.cos(el)*r,Math.sin(el)*r,Math.cos(az)*Math.cos(el)*r);sun.target.position.set(0,0,0);sun.intensity=state.day?state.sun:state.sun*.045;
  hemi.intensity=state.environment*(state.day?.8:.48);ambient.intensity=state.day?.12:.08;fill.intensity=state.day?.28:.05;S.environment=state.hdr?(probeOutput?.texture||envRT.texture):null;S.environmentIntensity=state.reflection*(state.day?1:.52);
  lightRig.lighting(state.lightPower,state.day);R.toneMappingExposure=state.exposure;R.shadowMap.enabled=state.shadows;invalidate(true);}
 function setDay(day){state.day=day;lighting();syncUI();}
 function quality(mode){cancelGesture();state.quality=mode;const size=mode==='photo'?3072:1536;if(sun.shadow.map){sun.shadow.map.dispose();sun.shadow.map=null;}sun.shadow.mapSize.set(size,size);layout(mode==='photo'?Math.min((devicePixelRatio||1)*1.5,2):Math.min(devicePixelRatio||1,1.35));invalidate(true);syncUI();}
 // Semantic entities use deterministic ids, not UUIDs. Stable across reload and JSON import.
 const entries=[],entityMap=new Map();
 function register(object,type,id,room){const e={id,type,object,room,name:object.userData.semantic||object.name,baseMaterials:new Map(),original:null};object.userData.entityId=id;object.userData.kind=type;object.traverse(o=>{if(o.isMesh)e.baseMaterials.set(o,o.material);});e.original=capture(e);entries.push(e);entityMap.set(id,e);return e;}
 for(let i=0;i<C.assets.length;i++){const o=C.assets[i];let r=o;while(r.parent&&r.parent!==root)r=r.parent;register(o,'furniture',o.userData.sourceId||('f'+String(i+1).padStart(3,'0')),r.name.replace(/^\d+\s*/,'').split(' · ')[0]);}
 walls.children.forEach((o,i)=>register(o,'wall',o.userData.sourceId||('w'+String(i+1).padStart(2,'0')),'建筑'));
 C.entities=entries;
 function capture(e){return{position:e.object.position.toArray(),rotation:e.object.rotation.toArray().slice(0,3),scale:e.object.scale.toArray(),visible:e.object.visible,style:e.object.userData.style||null};}
 const styleConfigs={cream:{color:'#e7e0d4',roughness:.92},oak:{color:'#c4a57d',roughness:.61},linen:{color:'#d5c7b6',roughness:.97},stone:{color:'#c9b99f',roughness:.65},clay:{color:'#b78a73',roughness:.87}};
 const styleCache=new Map();
 function setMaterialStyle(e,key){e.object.userData.style=key||null;const cfg=styleConfigs[key];for(const[o,original]of e.baseMaterials){if(!cfg){o.material=original;continue;}const originals=Array.isArray(original)?original:[original];const styled=originals.map(m=>{if(m.transparent||m.metalness>.5||(m.emissive&&m.emissive.getHex()!==0&&m.emissiveIntensity>0)||o.userData.noExport)return m;const k=m.uuid+'/'+key;if(styleCache.has(k))return styleCache.get(k);const c=m.clone();c.userData.cmfOverride=true;if(c.color)c.color.set(cfg.color);if('roughness'in c)c.roughness=cfg.roughness;styleCache.set(k,c);return c;});o.material=Array.isArray(original)?styled:styled[0];}}
 // Apply declarative placement overrides before capturing the reset baseline.
 for(const p of window.PROJECT.placements){const e=entityMap.get(p.id);if(e&&p.appearance)setMaterialStyle(e,p.appearance);if(e)e.original=capture(e);}
 function applySnapshot(e,s){e.object.position.fromArray(s.position);e.object.rotation.set(...s.rotation);e.object.scale.fromArray(s.scale);e.object.visible=s.visible;setMaterialStyle(e,s.style);e.object.updateMatrix();root.updateMatrixWorld(true);invalidate(true);}
 function record(e,before){if(e.type==='furniture'){const p=C.exportLayout(false);try{validateRuntimeLayout(p);}catch(err){applySnapshot(e,before);updateObjectUI();toast(err.message);return;}const check=Spatial.audit(C.exportLayout(false),e.id);if(check.errors.length){applySnapshot(e,before);updateObjectUI();toast('编辑未应用：'+check.errors.join(', '));return;}if(check.warnings.length)toast('已保留编辑，需核对净空：'+check.warnings.slice(0,4).join(', '));}const after=capture(e);if(JSON.stringify(before)===JSON.stringify(after))return;history.push({id:e.id,before,after});if(history.length>60)history.shift();redoHistory.length=0;syncUI();updateObjectUI();}
 function undo(){cancelGesture();const h=history.pop();if(!h)return;if(h.kind==='cmf')restoreCMF(h.before);else if(h.kind==='lighting'){lightRig.restore(h.before);updateLightUI();}else if(h.kind==='workspace')restoreWorkspace(h.before);else applySnapshot(entityMap.get(h.id),h.before);redoHistory.push(h);refreshLists();updateObjectUI();syncUI();invalidate(true);}
 function redo(){cancelGesture();const h=redoHistory.pop();if(!h)return;if(h.kind==='cmf')restoreCMF(h.after);else if(h.kind==='lighting'){lightRig.restore(h.after);updateLightUI();}else if(h.kind==='workspace')restoreWorkspace(h.after);else applySnapshot(entityMap.get(h.id),h.after);history.push(h);refreshLists();updateObjectUI();syncUI();invalidate(true);}
 function select(e){if(typeof e==='string')e=entityMap.get(e);if(e?.type==='wall'&&(state.wallLocked||state.tab!=='walls'))return;if(e?.type==='furniture'&&state.tab!=='furniture')return;
  if(helper){S.remove(helper);helper.geometry.dispose();helper.material.dispose();helper=null;}selected=e||null;
  if(selected){helper=new T.BoxHelper(selected.object,0xbd945f);helper.material.depthTest=true;helper.material.transparent=true;helper.material.opacity=.9;helper.userData.noExport=true;S.add(helper);$('#sel-name').textContent=selected.name;$('#sel-meta').textContent=selected.type==='furniture'?'独立家具 · '+selected.room:'固定建筑墙 · 仅显隐 / 材质';}
  $(`[data-panel="${state.tab}"]`).prepend($('#selection-card'));$('#selection-card').classList.toggle('show',!!selected);C.workspace?.selectedChanged();updateObjectUI();refreshLists();invalidate();}
 function updateObjectUI(){const editing=selected?.type==='furniture';$('#selection-empty').hidden=editing;$('#object-editor').hidden=!editing;if(!editing)return;const o=selected.object;$('#object-title').textContent=selected.name;
  const vals={'obj-x':o.position.x,'obj-y':o.position.y,'obj-z':o.position.z,'obj-yaw':T.MathUtils.radToDeg(o.rotation.y),'obj-scale':o.scale.x/selected.original.scale[0]};for(const[id,v]of Object.entries(vals))$('#'+id).value=Number(v.toFixed(id==='obj-yaw'?1:3));}
 function refreshLists(){
  const search=($('#asset-search').value||'').trim().toLowerCase();const list=$('#asset-list');list.replaceChildren();
  for(const e of entries.filter(e=>e.type==='furniture'&&(!search||(e.name+' '+e.room).toLowerCase().includes(search)))){const row=document.createElement('div');row.className='object-row'+(selected===e?' selected':'')+(!e.object.visible?' dim':'');row.dataset.entity=e.id;const name=document.createElement('span');name.textContent=e.name;const tag=document.createElement('small');tag.textContent=e.room;const eye=document.createElement('button');eye.textContent=e.object.visible?'◉':'○';eye.title='显示 / 隐藏';eye.onclick=ev=>{ev.stopPropagation();const b=capture(e);e.object.visible=!e.object.visible;record(e,b);refreshLists();invalidate(true);};row.append(name,tag,eye);row.onclick=()=>{select(e);if(state.tool==='browse'||state.tool==='select')setTool('move');};list.appendChild(row);}
  $('#asset-count').textContent=C.assets.length+' 个对象';
  const wallList=$('#wall-list');wallList.replaceChildren();for(const e of entries.filter(e=>e.type==='wall')){const row=document.createElement('div');row.className='wall-item'+(selected===e?' wall-selected':'');const ck=document.createElement('input');ck.type='checkbox';ck.checked=e.object.visible;ck.dataset.wall=e.id;const name=document.createElement('span');name.textContent=e.name;const button=document.createElement('button');button.textContent=state.wallLocked?'锁定':'选择';button.className=state.wallLocked?'locked':'';button.onclick=()=>{if(state.wallLocked)toast('先解锁墙体，才可选择墙面。家具操作不会移动墙体。');else select(e);};ck.onchange=()=>{const b=capture(e);e.object.visible=ck.checked;record(e,b);invalidate(true);};row.append(ck,name,button);wallList.appendChild(row);}}
 function validTransform(s){return s&&['position','rotation','scale'].every(k=>Array.isArray(s[k])&&s[k].length===3&&s[k].every(Number.isFinite))&&s.position.every(v=>Math.abs(v)<=50)&&s.rotation.every(v=>Math.abs(v)<=Math.PI*20)&&s.scale.every(v=>v>=.02&&v<=10)&&typeof s.visible==='boolean'&&(s.style===null||Object.hasOwn(styleConfigs,s.style));}
 function applyFields(){if(selected?.type!=='furniture')return;const e=selected,b=capture(e),n=structuredClone(b),x=Number($('#obj-x').value),y=Number($('#obj-y').value),z=Number($('#obj-z').value),yaw=Number($('#obj-yaw').value),scale=Number($('#obj-scale').value);
  if(![x,y,z,yaw,scale].every(Number.isFinite)||scale<.2||scale>3||Math.abs(x)>40||Math.abs(z)>40||y< -5||y>10){toast('输入超出范围：位置 ±40m，高度 -5～10m，缩放 0.2～3。');updateObjectUI();return;}n.position=[x,y,z];n.rotation[1]=T.MathUtils.degToRad(yaw);n.scale=e.original.scale.map(v=>v*scale);if(!validTransform(n)){toast('无效属性，未修改模型。');return;}applySnapshot(e,n);record(e,b);}
 function focusSelected(){if(!selected)return;cancelGesture();const box=new T.Box3().setFromObject(selected.object),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());active=cam;controls.camera=active;controls.mode='orbit';controls.twoPoint=false;const d=Math.max(2,size.length()*1.35);cam.position.copy(center).add(new T.Vector3(1,.7,1).normalize().multiplyScalar(d));controls.target.copy(center);cam.fov=50;cam.updateProjectionMatrix();controls.lookAt();state.view='free';state.roof=false;applyBuilding();syncUI();invalidate();}
 // Visible ancestor and cut-plane checks are performed before semantic promotion.
 const ray=new T.Raycaster(),ndc=new T.Vector2();
 function rayAt(x,y){const r=canvas.getBoundingClientRect();ndc.set((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1);active.updateMatrixWorld(true);root.updateMatrixWorld(true);ray.setFromCamera(ndc,active);return ray;}
 function isVisible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
 function pick(x,y){if(!['walls','furniture'].includes(state.tab))return null;rayAt(x,y);const hits=ray.intersectObject(root,true);for(const h of hits){const o=h.object;if(!isVisible(o)||o.userData.noExport)continue;const mat=Array.isArray(o.material)?o.material[0]:o.material;if(state.cut&&mat.clippingPlanes?.some(p=>p.distanceToPoint(h.point)<0))continue;
   let p=o;while(p&&p!==root&&!p.userData.entityId)p=p.parent;const e=p?entityMap.get(p.userData.entityId):null;
   if(e?.type==='furniture'&&state.tab==='furniture')return{entry:e,point:h.point};if(e?.type==='wall'&&state.tab==='walls'&&!state.wallLocked)return{entry:e,point:h.point};
   // Opaque architecture blocks picking through walls, but transparent glass does not.
   if(!mat.transparent)return null;
  }return null;}
 C.pick=pick;
 function planeHit(x,y,height){rayAt(x,y);return ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-height),new T.Vector3());}
 function endGesture(commit=true){const g=gesture;gesture=null;pointers.clear();if(g?.kind==='light'){if(commit)recordLighting(g.before);else lightRig.restore(g.before);updateLightUI();}if(g?.entity){if(commit)record(g.entity,g.before);else applySnapshot(g.entity,g.before);updateObjectUI();}for(const id of[g?.id])if(id!=null&&canvas.hasPointerCapture(id))try{canvas.releasePointerCapture(id);}catch{}invalidate();}
 function cancelGesture(){endGesture(false);}
 function cameraMoved(){state.auto=false;syncUI();invalidate();}
 canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('pointerdown',e=>{if(state.busy||rendering||contextLost||e.button>2)return;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});state.auto=false;
  if(pointers.size===2){if(gesture?.kind==='light')lightRig.restore(gesture.before);if(gesture?.entity)applySnapshot(gesture.entity,gesture.before);const p=[...pointers.values()];gesture={kind:'pinch',distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),center:{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}};return;}
  if(pointers.size>2)return;const g=gesture={id:e.pointerId,button:e.button,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,kind:'camera'};
  if(e.button===0&&state.tab==='furniture'&&['move','rotate'].includes(state.tool)&&!e.altKey){const hit=pick(e.clientX,e.clientY);if(hit?.entry.type==='furniture'){select(hit.entry);g.entity=hit.entry;g.before=capture(hit.entry);g.kind=state.tool;g.world=hit.entry.object.getWorldPosition(new T.Vector3());g.plane=planeHit(e.clientX,e.clientY,g.world.y);}}
  if(e.button===0&&state.tab==='lights'&&!e.altKey){rayAt(e.clientX,e.clientY);let item=lightRig.pick(ray);
   if(!item){const hit=ray.intersectObject(root,true).find(h=>beyondNear(h,camera)&&isVisible(h.object)&&!h.object.userData.noExport&&!h.object.material?.transparent);let o=hit?.object;while(o&&o!==root&&!o.userData.entityId)o=o.parent;if(o)item=[...lightRig.items.values()].find(l=>l.data.anchorId===o.userData.entityId);}
   if(item){lightRig.select(item.data.id);g.kind='light';g.lightId=item.data.id;g.before=lightRig.serialize();g.world=new T.Vector3(...item.data.position);g.plane=planeHit(e.clientX,e.clientY,g.world.y);updateLightUI();invalidate();}}
 });
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture;
  if(pointers.size===2&&g.kind==='pinch'){const p=[...pointers.values()],d=Math.max(1,Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)),c={x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2};controls.zoom(Math.log(Math.max(1,g.distance)/d));controls.pan(c.x-g.center.x,c.y-g.center.y);g.distance=d;g.center=c;cameraMoved();return;}
  if(e.pointerId!==g.id)return;const dx=e.clientX-g.lastX,dy=e.clientY-g.lastY;g.lastX=e.clientX;g.lastY=e.clientY;g.moved ||=Math.hypot(e.clientX-g.x,e.clientY-g.y)>5;if(!g.moved)return;
  if(g.kind==='light'){if(g.plane){const p=planeHit(e.clientX,e.clientY,g.world.y);if(p){const world=g.world.clone().add(p.sub(g.plane));world.x=T.MathUtils.clamp(world.x,-40,40);world.z=T.MathUtils.clamp(world.z,-40,40);lightRig.move(g.lightId,world.toArray());updateLightUI(false);invalidate(true);}}}
  else if(g.entity){const o=g.entity.object;if(g.kind==='move'&&g.plane){const p=planeHit(e.clientX,e.clientY,g.world.y);if(p){const world=g.world.clone().add(p.sub(g.plane)),local=o.parent.worldToLocal(world),snap=+$('#snap').value||0;if(snap){local.x=Math.round(local.x/snap)*snap;local.z=Math.round(local.z/snap)*snap;}local.x=T.MathUtils.clamp(local.x,-40,40);local.z=T.MathUtils.clamp(local.z,-40,40);o.position.copy(local);}}else if(g.kind==='rotate'){let a=g.before.rotation[1]+(e.clientX-g.x)*.009;if(e.shiftKey)a=Math.round(a/(Math.PI/12))*(Math.PI/12);o.rotation.y=a;}o.updateMatrix();updateObjectUI();invalidate(true);}
  else{if(g.button===2||e.shiftKey||active.isOrthographicCamera)controls.pan(dx,dy);else controls.rotate(dx,dy);cameraMoved();}
 });
 canvas.addEventListener('pointerup',e=>{const g=gesture;if(!g)return;const click=g.id===e.pointerId&&!g.moved&&g.button===0&&!g.entity&&g.kind!=='light';endGesture(true);if(click&&state.tab==='lights'){lightRig.select(null);updateLightUI();invalidate();}else if(click&&['walls','furniture'].includes(state.tab)){const h=pick(e.clientX,e.clientY);select(h?.entry||null);}});
 canvas.addEventListener('pointercancel',cancelGesture);canvas.addEventListener('lostpointercapture',e=>{if(gesture?.id===e.pointerId)cancelGesture();});window.addEventListener('blur',cancelGesture);
 canvas.addEventListener('wheel',e=>{if(state.busy||gesture?.entity)return;e.preventDefault();controls.zoom(T.MathUtils.clamp(e.deltaY,-160,160)*.0018);cameraMoved();},{passive:false});
 window.addEventListener('keydown',e=>{if(state.busy)return;if(e.target.closest('input,select,textarea'))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();redo();return;}if(k==='escape'){cancelGesture();select(null);setTool(state.tab==='furniture'?'move':'browse');return;}if(k==='f'){focusSelected();return;}if(['arrowleft','arrowright','arrowup','arrowdown'].includes(k)){e.preventDefault();const s=e.shiftKey?.35:.16;if(controls.mode==='look'){controls.walk(k==='arrowup'?s:k==='arrowdown'?-s:0,k==='arrowright'?s:k==='arrowleft'?-s:0,0);}else controls.pan(k==='arrowleft'?18:k==='arrowright'?-18:0,k==='arrowup'?18:k==='arrowdown'?-18:0);cameraMoved();}});
 // Screen labels always use the same active camera as drawing and picking.
 const labelEls=[];for(const room of C.rooms){const el=document.createElement('button');el.className='room-label';el.textContent=room.name;el.onclick=()=>setView(room.id);$('#labels').appendChild(el);labelEls.push({el,p:new T.Vector3(room.point[0],.2,room.point[2])});}
 function updateLabels(){const show=state.labels;$('#labels').style.display=show?'block':'none';if(show)for(const{el,p}of labelEls){const v=p.clone().project(active);el.style.left=(v.x*.5+.5)*stage.clientWidth+'px';el.style.top=(-v.y*.5+.5)*stage.clientHeight+'px';el.style.visibility=Math.abs(v.x)<1&&Math.abs(v.y)<1&&v.z<1?'visible':'hidden';}const a=new T.Vector3().project(active),b=new T.Vector3(0,0,-2).project(active);$('#north-arrow').style.transform=`rotate(${Math.atan2(-(b.y-a.y),b.x-a.x)*180/Math.PI+90}deg)`;}
 function cameraSnapshot(){return{near:active.near,type:active.isOrthographicCamera?'orthographic':'perspective',position:active.position.toArray(),target:controls.target.toArray(),fov:cam.fov,verticalShift:cam.view?.enabled?-2*cam.view.offsetY/cam.view.fullHeight:0,zoom:active.zoom,mode:controls.mode,twoPoint:controls.twoPoint,view:state.view,roof:state.roof,cut:state.cut,labels:state.labels};}
 function validateCamera(x){return x&&(x.near===undefined||(Number.isFinite(x.near)&&x.near>0&&x.near<100))&&(x.verticalShift===undefined||Number.isFinite(x.verticalShift))&&['position','target'].every(k=>Array.isArray(x[k])&&x[k].length===3&&x[k].every(v=>Number.isFinite(v)&&Math.abs(v)<200))&&Number.isFinite(x.fov)&&x.fov>=20&&x.fov<=120&&['perspective','orthographic'].includes(x.type)&&Number.isFinite(x.zoom)&&x.zoom>=.1&&x.zoom<=20&&['orbit','look'].includes(x.mode)&&Math.hypot(...x.position.map((v,i)=>v-x.target[i]))>.05;}
 function restoreCamera(x){if(!validateCamera(x))throw Error('机位数据无效');cancelGesture();active=x.type==='orthographic'?ortho:cam;controls.camera=active;active.position.fromArray(x.position);controls.target.fromArray(x.target);cam.fov=x.fov;active.near=x.near||.04;active.zoom=x.zoom;controls.mode=x.mode;controls.twoPoint=!!x.twoPoint;cam.setViewOffset(cam.aspect,1,0,-(x.verticalShift||0)/2,cam.aspect,1);cam.updateProjectionMatrix();ortho.updateProjectionMatrix();controls.lookAt();state.view=x.view||'free';state.roof=!!x.roof;state.cut=!!x.cut;state.labels=!!x.labels;ground.visible=['overview','plan'].includes(state.view);applyBuilding();syncUI();}
 function saveCamera(){savedCameras.push({name:(C.presets[state.view]?.title||'自由机位')+' '+(savedCameras.length+1),camera:cameraSnapshot()});if(savedCameras.length>20)savedCameras.shift();try{localStorage.setItem('interior-cameras-'+window.PROJECT.id,JSON.stringify(savedCameras));}catch{}refreshCameras();toast('机位已保存；保存方案 JSON 也会包含机位。');}
 function refreshCameras(){const list=$('#saved-cameras');list.replaceChildren();savedCameras.forEach((x,i)=>{const row=document.createElement('div');row.className='object-row';const label=document.createElement('span');label.textContent=x.name;const del=document.createElement('button');del.textContent='×';del.title='删除机位';del.onclick=e=>{e.stopPropagation();savedCameras.splice(i,1);try{localStorage.setItem('interior-cameras-'+window.PROJECT.id,JSON.stringify(savedCameras));}catch{}refreshCameras();};row.append(label,del);row.onclick=()=>restoreCamera(x.camera);list.appendChild(row);});}
 async function updateProbe(){if(state.busy)return;const button=$('#probe-update');button.disabled=true;cancelGesture();const oldTarget=R.getRenderTarget(),oldEnv=S.environment,visible=helper?.visible;try{busy('正在更新室内反射探针…');await paintPause();if(helper)helper.visible=false;const rt2=new T.WebGLCubeRenderTarget(128,{type:T.HalfFloatType,generateMipmaps:true,minFilter:T.LinearMipmapLinearFilter}),probe=new T.CubeCamera(.08,60,rt2);probe.position.copy(active.position);probe.position.y=T.MathUtils.clamp(probe.position.y,.7,2.25);S.environment=envRT.texture;safeClear(null);probe.update(R,S);const pm=new T.PMREMGenerator(R),output=pm.fromCubemap(rt2.texture);pm.dispose();probeRT?.dispose();probeOutput?.dispose();probeRT=rt2;probeOutput=output;S.environment=state.hdr?output.texture:null;toast('反射探针已更新。场景变化后可再次手动更新。');}catch(e){S.environment=oldEnv;fail(e);}finally{if(helper)helper.visible=visible;R.setRenderTarget(oldTarget);R.state.buffers.depth.setMask(true);R.state.buffers.color.setMask(true);button.disabled=false;busy(null);invalidate(true);}}
 async function exportPNG(multiplier=1){if(state.busy)return;const buttons=[$('#export-photo')];buttons.forEach(b=>b.disabled=true);cancelGesture();const ratio=R.getPixelRatio(),helperVisible=helper?.visible;try{busy('正在导出 PNG，请稍候…');await paintPause();if(helper)helper.visible=false;const limit=Math.min(R.capabilities.maxTextureSize,4096),targetRatio=Math.min(ratio*multiplier,limit/Math.max(stage.clientWidth,stage.clientHeight));layout(targetRatio);draw();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PNG 编码失败')),'image/png'));C.downloadBlob(blob,`interior-${C.activeStyle.id}-${state.view}-${canvas.width}x${canvas.height}.png`);toast(`已导出 ${canvas.width} × ${canvas.height} PNG`);}catch(e){fail(e);}finally{layout(ratio);if(helper)helper.visible=helperVisible;buttons.forEach(b=>b.disabled=false);busy(null);invalidate(true);}}
 const lightSettings=['day','exposure','sun','azimuth','elevation','environment','reflection','lightPower','shadows','hdr'];
 const viewSettings=['wallVisible','furnitureVisible','ao','direct','doors'];
 let immutableStructure=JSON.stringify({floor:window.PROJECT.floor,rooms:window.PROJECT.rooms,walls:window.PROJECT.walls,openings:window.PROJECT.openings,openConnections:window.PROJECT.openConnections});
 function exportProject(){return{schema:'interior.editor/2',structureKey:window.STRUCTURE_KEY,layout:C.exportLayout(false),styleRecipe:structuredClone(C.activeStyle),display:entries.map(e=>({id:e.id,visible:e.object.visible})),view:Object.fromEntries(viewSettings.map(k=>[k,state[k]])),camera:cameraSnapshot(),cameras:structuredClone(savedCameras)};}
 function validateRuntimeLayout(p){const errors=Spatial.validateStructure(p);if(errors.length)throw Error(errors.join('; '));if(p.id!==window.PROJECT.id)throw Error('编辑快照属于不同项目，请打开对应完整HTML');const assets=new Map();for(const a of p.nativeAssets||[]){C.nativeAssets.validateRecord(a);if(assets.has(a.id))throw Error('重复原生资产ID');assets.set(a.id,a);}for(const x of p.placements){if(!window.COMPONENT_CATALOG.components.some(c=>c.id===x.componentId))throw Error('未知组件 '+x.componentId);if(x.nativeAssetId){const a=assets.get(x.nativeAssetId);if(!a||a.componentId!==x.componentId)throw Error('原生资产引用/类别不一致');const ratio=x.size.map((v,i)=>v/a.size[i]);if((a.deform||'uniform')==='uniform'&&Math.max(...ratio)-Math.min(...ratio)>.002)throw Error('此资产只允许等比缩放，不接受分轴拉伸');}for(const v of Object.values(x.materialOverrides||{})){if(v.color!==undefined&&!/^#[0-9a-f]{6}$/i.test(v.color))throw Error('材质颜色无效');for(const k of ['roughness','metalness'])if(v[k]!==undefined&&(!Number.isFinite(v[k])||v[k]<0||v[k]>1))throw Error('材质参数越界');}}C.validateLights(p.lighting?.lights||[]);if(p.lighting?.settings){const ranges={exposure:[.4,1.5],sun:[0,4],azimuth:[0,360],elevation:[8,80],environment:[.1,1.5],reflection:[0,1.8],lightPower:[0,2.5]};for(const[k,v]of Object.entries(p.lighting.settings)){if(ranges[k]){if(!Number.isFinite(v)||v<ranges[k][0]||v>ranges[k][1])throw Error('光照设置越界');}else if(!['day','shadows','hdr'].includes(k)||typeof v!=='boolean')throw Error('未知光照设置');}}return true;}

 async function importProject(data){if(data?.schema!=='interior.editor/2')throw Error('编辑快照格式不匹配');C.validateStyle(data.styleRecipe);validateRuntimeLayout(data.layout);if(data.layout.styleId!==data.styleRecipe.id)throw Error('风格绑定不一致');if(!validateCamera(data.camera)||!Array.isArray(data.cameras)||data.cameras.length>20||data.cameras.some(x=>typeof x.name!=='string'||!validateCamera(x.camera)))throw Error('机位无效');const ids=new Set([...data.layout.placements,...data.layout.walls].map(x=>x.id));if(!Array.isArray(data.display)||data.display.length!==ids.size||data.display.some(x=>!ids.has(x.id)||typeof x.visible!=='boolean')||new Set(data.display.map(x=>x.id)).size!==ids.size)throw Error('对象显示值无效');for(const k of viewSettings)if(typeof data.view?.[k]!=='boolean')throw Error('显示状态无效');await C.nativeAssets.prepare(data.layout.nativeAssets||[]);
  rebuild(data.layout,data.styleRecipe);for(const x of data.display)entityMap.get(x.id).object.visible=x.visible;Object.assign(state,data.view,data.layout.lighting?.settings||{});if(data.layout.lighting)lightRig.restore(data.layout.lighting.lights);savedCameras=structuredClone(data.cameras);restoreCamera(data.camera);lighting();syncLightFields();refreshCameras();refreshLists();updateLightUI();syncUI();C.workspace?.refresh();invalidate(true);}
 function layoutTransaction(next,recipe=C.activeStyle){validateRuntimeLayout(next);const before=exportProject(),camState=cameraSnapshot(),oldHistory=[...history];next.revision=(window.PROJECT.revision||1)+1;next.customStyle=structuredClone(recipe);rebuild(next,recipe);if(next.lighting)lightRig.restore(next.lighting.lights);history.push(...oldHistory,{kind:'workspace',before,after:exportProject()});if(history.length>60)history.splice(0,history.length-60);redoHistory.length=0;restoreCamera(camState);window.SCENE_KEY='edited-'+T.MathUtils.generateUUID();C.workspace?.refresh();syncUI();invalidate(true);}
 async function applyWorkspace(next){await C.nativeAssets.prepare(next.nativeAssets||[]);layoutTransaction(next);}
 function restoreWorkspace(snapshot){const camState=cameraSnapshot(),h=[...history],r=[...redoHistory];rebuild(snapshot.layout,snapshot.styleRecipe);snapshot.display.forEach(x=>{const e=entityMap.get(x.id);if(e)e.object.visible=x.visible;});if(snapshot.layout.lighting)lightRig.restore(snapshot.layout.lighting.lights);history.push(...h);redoHistory.push(...r);restoreCamera(camState);C.workspace?.refresh();}
 function syncLightFields(){for(const[id,k]of Object.entries({'sun-power':'sun','sun-azimuth':'azimuth','sun-height':'elevation','env-power':'environment','light-power':'lightPower','reflection-power':'reflection','render-exposure':'exposure'})){$('#'+id).value=state[k];output(id,Number(state[k]).toFixed(2));}}
 // Scoped light editing shares the same undo history and pointer owner as furniture.
 function recordLighting(before){const after=lightRig.serialize();if(JSON.stringify(before)===JSON.stringify(after))return;history.push({kind:'lighting',before,after});if(history.length>60)history.shift();redoHistory.length=0;syncUI();updateLightUI();invalidate(true);}
 function syncLinkedLights(){if(!C.entities)return;for(const e of lightRig.items.values()){const d=e.data;if(!d.anchorId)continue;const entity=entityMap.get(d.anchorId),spec=window.PROJECT.placements.find(x=>x.id===d.anchorId);if(!entity||!spec)continue;const o=entity.object,y=o.position.y+spec.size[1]*o.scale.y/entity.original.scale[1]*(d.anchorFraction??.55),pos=[o.position.x,y,o.position.z];if(Math.hypot(...pos.map((x,i)=>x-d.position[i]))>.00001)lightRig.move(d.id,pos,false);}}
 function updateLightUI(relist=true){const current=lightRig.get(lightRig.selected),d=current?.data;$('#light-properties').hidden=!d;
  if(d){$('#light-title').textContent=d.name;$('#light-binding').textContent=d.anchorId?'跟随灯具':'独立光源';for(const[id,k]of Object.entries({'light-intensity':'intensity','light-temperature':'temperature','light-distance':'distance','light-angle':'angle','light-penumbra':'penumbra'}))$('#'+id).value=d[k];for(const[k,prefix]of [['position','light'],['target','target']])for(const[i,axis]of ['x','y','z'].entries())$('#'+prefix+'-'+axis).value=Number(d[k][i].toFixed(3));$('#light-enabled').checked=d.enabled;$('#light-shadow').checked=d.castShadow;$('#spot-fields').hidden=d.type!=='spot';}
  if(relist){const list=$('#light-list');list.replaceChildren();for(const e of lightRig.items.values()){const x=e.data,row=document.createElement('div');row.className='object-row'+(x.id===lightRig.selected?' selected':'')+(!x.enabled?' dim':'');row.dataset.light=x.id;const name=document.createElement('span');name.textContent=x.name;const meta=document.createElement('small');meta.textContent=(x.type==='spot'?'射灯':'点光')+' · '+x.temperature+'K';const toggle=document.createElement('button');toggle.textContent=x.enabled?'◉':'○';toggle.title='开 / 关';toggle.onclick=ev=>{ev.stopPropagation();try{const before=lightRig.serialize();lightRig.update(x.id,{enabled:!x.enabled});recordLighting(before);}catch(e){toast(e.message);}};row.append(name,meta,toggle);row.onclick=()=>{if(state.tab!=='lights')return;lightRig.select(x.id);updateLightUI();invalidate();};list.appendChild(row);}}
 }
 function addLight(type){if(state.tab!=='lights'||state.busy)return;try{const before=lightRig.serialize(),pos=controls.target.clone();pos.y=Math.min(2.4,window.PROJECT.floor.height-.18);pos.x=T.MathUtils.clamp(pos.x,C.sceneBounds.minX+.3,C.sceneBounds.maxX-.3);pos.z=T.MathUtils.clamp(pos.z,C.sceneBounds.minZ+.3,C.sceneBounds.maxZ-.3);lightRig.add(type,pos.toArray(),[pos.x,.05,pos.z],C.activeStyle.lighting.temperature);recordLighting(before);updateLightUI();}catch(e){toast(e.message);}}
 function applyLightFields(){const e=lightRig.get(lightRig.selected);if(!e||state.tab!=='lights')return;try{const before=lightRig.serialize(),patch={position:['x','y','z'].map(k=>Number($('#light-'+k).value)),target:['x','y','z'].map(k=>Number($('#target-'+k).value)),intensity:Number($('#light-intensity').value),temperature:Number($('#light-temperature').value),distance:Number($('#light-distance').value),angle:Number($('#light-angle').value),penumbra:Number($('#light-penumbra').value),enabled:$('#light-enabled').checked,castShadow:e.data.type==='spot'&&$('#light-shadow').checked};
   if(patch.position.some((v,i)=>Math.abs(v-e.data.position[i])>.0001))patch.anchorId=null;lightRig.update(e.data.id,patch);recordLighting(before);updateLightUI();}catch(err){toast(err.message);updateLightUI();}}
 function refreshStyleUI(previewId){const catalog=window.STYLE_CATALOG.styles;const control=$('#style-select'),prior=previewId||C.activeStyle.id;control.replaceChildren();for(const s of catalog){const opt=document.createElement('option');opt.value=s.id;opt.textContent=s.name;control.appendChild(opt);}control.value=prior;const style=catalog.find(x=>x.id===prior)||C.activeStyle;
  const palette=$('#style-palette');palette.replaceChildren();for(const color of style.palette){const el=document.createElement('span');el.style.background=color;el.title=color;palette.appendChild(el);}
  const desc=$('#style-description');desc.replaceChildren();for(const[k,title]of [['intent','主题'],['forms','形状'],['materials','材质'],['details','细节'],['lighting','打灯']]){const p=document.createElement('p'),b=document.createElement('b');b.textContent=title+' · ';p.append(b,document.createTextNode(style.playbook[k]));desc.appendChild(p);}
  $('#style-shape-count').textContent='29 类组件 · CMF 独立切换 · 本地家具库';$('#project-title').textContent=window.PROJECT.name.split(' · ')[0];$('#style-caption').textContent=C.activeStyle.name+' / '+C.activeStyle.englishName;$('#style-label').textContent=C.activeStyle.name;document.title=window.PROJECT.name.split(' · ')[0]+' · '+C.activeStyle.name+' · INTERIOR STUDIO';document.documentElement.style.setProperty('--accent',C.activeStyle.theme.accent);S.background.set(C.activeStyle.theme.background||'#d8d4cc');ground.material.color.set(C.activeStyle.theme.background||'#ded8ce');
 }
 function disposeSceneGeometry(){const geometry=new Set(),mats=new Set(),preserve=new Set(Object.values(C.M)),cached=new Set(C.geometryCache.values());root.traverse(o=>{if(o.geometry&&!cached.has(o.geometry))geometry.add(o.geometry);for(const m of(o.material?Array.isArray(o.material)?o.material:[o.material]:[]))if(!preserve.has(m))mats.add(m);});geometry.forEach(g=>g.dispose());mats.forEach(m=>{if(m.name?.startsWith('原创')&&m.map)m.map.dispose();m.dispose();});styleCache.forEach(m=>m.dispose());styleCache.clear();root.clear();}
 function rebuild(data,recipe){C.validateStyle(recipe);cancelGesture();select(null);lightRig.select(null);const visibility=new Map(entries.map(e=>[e.id,e.object.visible]));disposeSceneGeometry();window.PROJECT=structuredClone(data);let existing=window.STYLE_CATALOG.styles.findIndex(s=>s.id===recipe.id);if(existing>=0)window.STYLE_CATALOG.styles[existing]=structuredClone(recipe);else window.STYLE_CATALOG.styles.push(structuredClone(recipe));window.PROJECT.styleId=recipe.id;
  C.buildScene(root,window.PROJECT);C.optimizeLocal(root);walls=C.walls=C.architecture.getObjectByName('完整墙体与洞口');furnitureGroups=root.children.filter(o=>o!==C.architecture&&o!==C.ceiling);entries.length=0;entityMap.clear();
  for(const o of C.assets){const e=register(o,'furniture',o.userData.sourceId,o.parent.name);const p=window.PROJECT.placements.find(x=>x.id===e.id);if(p?.appearance)setMaterialStyle(e,p.appearance);e.original=capture(e);if(visibility.has(e.id))e.object.visible=visibility.get(e.id);}
  walls.children.forEach(o=>{const e=register(o,'wall',o.userData.sourceId,'建筑');if(visibility.has(e.id))e.object.visible=visibility.get(e.id);});history.length=0;redoHistory.length=0;probeOutput?.dispose();probeOutput=null;probeRT?.dispose();probeRT=null;S.environment=state.hdr?envRT.texture:null;recount();applyBuilding();refreshLists();refreshStyleUI();syncUI();invalidate(true);
 }
 function restoreCMF(recipe){C.validateStyle(recipe);C.applyStyleRecipe(structuredClone(recipe));window.PROJECT.styleId=recipe.id;window.PROJECT.customStyle=structuredClone(recipe);window.SCENE_KEY='edited-'+T.MathUtils.generateUUID();refreshStyleUI();invalidate(true);}
 async function applyStyle(id){if(state.busy)return;const recipe=window.STYLE_CATALOG.styles.find(s=>s.id===id);if(!recipe){toast('风格不存在');return;}if(recipe.id===C.activeStyle.id){refreshStyleUI();return;}const before=structuredClone(C.activeStyle),after=structuredClone(recipe);after.forms=structuredClone(before.forms);after.lighting=structuredClone(before.lighting);try{C.validateStyle(after);restoreCMF(after);window.PROJECT.revision+=1;history.push({kind:'cmf',before,after});redoHistory.length=0;syncUI();toast('仅应用 CMF；家具造型、位置、相机、灯光和撤销记录保留。独立 GLB 材质保持原样，可在家具面板调整。');}catch(e){fail(e);}}
 // Every DOM event below is registered exactly once.
 $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>{cancelGesture();if(active.isOrthographicCamera){toast('正交平面仅平移。请先选择三维机位。');return;}controls.mode=b.dataset.nav;controls.twoPoint=false;syncUI();}));
 $('#quick-view').onchange=e=>setView(e.target.value);$('#home-view').onclick=()=>setView('overview');$('#reset-view').onclick=()=>setView(C.presets[state.view]?state.view:'overview');
 $('#wall-lock').onclick=()=>{state.wallLocked=!state.wallLocked;if(state.wallLocked&&selected?.type==='wall')select(null);syncUI();refreshLists();};
 for(const[id,key]of Object.entries({'wall-vis':'wallVisible','furniture-vis':'furnitureVisible','doors':'doors','labels-toggle':'labels','auto':'auto','roof':'roof','cut':'cut'}))$('#'+id).onchange=e=>{state[key]=e.target.checked;if(key==='cut'&&state.cut)state.roof=false;if(key==='roof'&&state.roof)state.cut=false;if(key==='auto'&&state.auto){controls.mode='orbit';controls.twoPoint=false;setTool('browse');state.auto=true;}applyBuilding();syncUI();};
 $('#day').onclick=()=>setDay(true);$('#night').onclick=()=>setDay(false);
 for(const[id,key]of Object.entries({'sun-power':'sun','sun-azimuth':'azimuth','sun-height':'elevation','env-power':'environment','light-power':'lightPower','reflection-power':'reflection','render-exposure':'exposure'}))$('#'+id).oninput=e=>{state[key]=+e.target.value;output(id,Number(state[key]).toFixed(2));lighting();};
 $('#camera-fov').oninput=e=>{if(active.isOrthographicCamera)return;cam.fov=+e.target.value;cam.updateProjectionMatrix();output('camera-fov',cam.fov+'°');invalidate();};
 $('#two-point').onchange=e=>{controls.twoPoint=e.target.checked;if(controls.twoPoint){controls.target.y=active.position.y;if(active.position.distanceTo(controls.target)<.1)controls.target.z-=1;controls.lookAt();}invalidate();};
 $('#asset-search').oninput=refreshLists;$('#apply-transform').onclick=applyFields;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#focus-object').onclick=focusSelected;
 $('#reset-object').onclick=()=>{if(!selected)return;const before=capture(selected);applySnapshot(selected,selected.original);record(selected,before);};$('#hide-object').onclick=()=>{if(!selected)return;const before=capture(selected);selected.object.visible=false;record(selected,before);refreshLists();invalidate(true);};$('#restore-furniture').onclick=()=>{state.furnitureVisible=true;for(const e of entries.filter(e=>e.type==='furniture'))e.object.visible=true;applyBuilding();refreshLists();syncUI();};
 $('#material-swatches').onclick=e=>{const key=e.target.closest('[data-mat]')?.dataset.mat;if(!key||!selected)return;const before=capture(selected);setMaterialStyle(selected,key);record(selected,before);invalidate();};
 $('#quality-live').onclick=()=>quality('live');$('#quality-photo').onclick=()=>quality('photo');$('#render-ao').onchange=e=>{state.ao=e.target.checked;invalidate();};$('#render-direct').onchange=e=>{state.direct=e.target.checked;invalidate();};$('#render-shadow').onchange=e=>{state.shadows=e.target.checked;lighting();};$('#hdr-env').onchange=e=>{state.hdr=e.target.checked;lighting();};$('#probe-update').onclick=updateProbe;
 $('#save-camera').onclick=saveCamera;
 $('#export-photo').onclick=()=>exportPNG(+$('#supersample').value||2);
 $('#export-glb').onclick=async()=>{if(state.busy)return;const b=$('#export-glb');b.disabled=true;cancelGesture();try{busy('正在打包完整 GLB 模型…');await paintPause();const bytes=await C.exportGLB(root);C.downloadBlob(new Blob([bytes],{type:'model/gltf-binary'}),'interior-studio-edited.glb');toast('已导出完整建筑与当前家具变换。视口剖切不写入 GLB。');}catch(e){fail(e);}finally{b.disabled=false;busy(null);}};
 $('#save-project').onclick=()=>C.downloadBlob(new Blob([JSON.stringify(exportProject(),null,2)],{type:'application/json'}),'interior-studio-project.json');$('#load-project').onclick=()=>$('#project-file').click();$('#project-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>120e6)throw Error('方案文件超过 120 MB，请精简使用资产');await importProject(JSON.parse(await file.text()));toast('方案已恢复。');}catch(err){fail(err);}finally{e.target.value='';}};
 $('#reset-all').onclick=()=>{if(!confirm('将丢弃本次修改并恢复模型初始位置。继续？'))return;cancelGesture();select(null);entries.forEach(e=>applySnapshot(e,e.original));history.length=0;redoHistory.length=0;state.wallVisible=state.furnitureVisible=true;setView('overview');refreshLists();syncUI();};
 $('#rotate-90').onclick=()=>{if(state.tab!=='furniture'||selected?.type!=='furniture'){toast('先选择一个活动家具');return;}cancelGesture();const before=capture(selected);selected.object.rotation.y=((selected.object.rotation.y+Math.PI/2+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;selected.object.updateMatrix();record(selected,before);updateObjectUI();invalidate(true);};
 $('#add-point').onclick=()=>addLight('point');$('#add-spot').onclick=()=>addLight('spot');$('#apply-light').onclick=applyLightFields;$('#delete-light').onclick=()=>{if(state.tab!=='lights'||!lightRig.selected)return;const before=lightRig.serialize();lightRig.remove(lightRig.selected);recordLighting(before);updateLightUI();};
 $('#style-lighting').onclick=()=>{try{const before=lightRig.serialize();lightRig.restore(C.defaultLights(C.exportLayout(false),C.rooms,C.activeStyle));lightRig.show(true);recordLighting(before);lighting();updateLightUI();toast('已恢复当前风格的默认光源，可撤销。');}catch(e){toast(e.message);}};
 $('#style-select').onchange=e=>refreshStyleUI(e.target.value);$('#apply-style').onclick=()=>applyStyle($('#style-select').value);$('#import-style').onclick=()=>$('#style-file').click();$('#style-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>128000)throw Error('风格JSON超过128KB');const recipe=JSON.parse(await file.text());C.validateStyle(recipe);if(window.STYLE_CATALOG.styles.some(s=>s.id===recipe.id))throw Error('已有同名风格，请修改JSON id后导入');window.STYLE_CATALOG.styles.push(recipe);refreshStyleUI(recipe.id);toast('风格已载入，点击应用；保存方案会携带完整配方。');}catch(err){toast(err.message);}finally{e.target.value='';}};
 $('#export-style').onclick=()=>C.downloadBlob(new Blob([JSON.stringify(C.activeStyle,null,2)],{type:'application/json'}),C.activeStyle.id+'-playbook.json');
 $('#menu').onclick=()=>document.body.classList.toggle('panel-open');$('#close-panel').onclick=()=>document.body.classList.remove('panel-open');
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;cancelGesture();toast('图形上下文暂时中断。请先保存方案；恢复后会重绘。');$('#health').textContent='图形上下文暂停';});canvas.addEventListener('webglcontextrestored',()=>{contextLost=false;layout();invalidate(true);$('#health').textContent='图形上下文已恢复';});
 function recount(){let meshes=0,triangles=0;root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);}});C.stats={engine:'Three.js r'+T.REVISION,version:state.version,meshes,originalMeshes,triangles,semanticAssets:C.assets.length,walls:walls.children.length,rooms:C.rooms.length,offline:true};}
 recount();
 C.exportLayout=function(increment=true){syncLinkedLights();const data=structuredClone(window.PROJECT);if(increment){data.revision+=1;data.source.assumptions.push('由通用 HTML 编辑器导出；结构、风格、原生资产、家具属性、量尺与光源按当前状态保存；需重编译场景与机位。');}
 data.styleId=C.activeStyle.id;data.lighting={schema:'interior.lighting/1',lights:lightRig.serialize(),settings:Object.fromEntries(lightSettings.map(k=>[k,state[k]]))};
 for(const p of data.placements){const e=entityMap.get(p.id);if(!e)continue;p.position=e.object.position.toArray();p.rotationY=((T.MathUtils.radToDeg(e.object.rotation.y)+180)%360+360)%360-180;p.size=p.size.map((v,i)=>v*(e.object.scale.getComponent(i)/e.original.scale[i]));p.appearance=e.object.userData.style||null;}
 const used=new Set(data.placements.map(p=>p.nativeAssetId).filter(Boolean));data.nativeAssets=(data.nativeAssets||[]).filter(a=>used.has(a.id));data.customStyle=structuredClone(C.activeStyle);return data;};
 $('#export-layout').onclick=()=>C.downloadBlob(new Blob([JSON.stringify(C.exportLayout(),null,2)],{type:'application/json'}),'layout.json');
 C.getDiagnostics=()=>({...C.stats,view:state.view,activeCamera:active.isOrthographicCamera?'orthographic':'perspective',camera:active.position.toArray(),target:controls.target.toArray(),renderCount:state.renderCount,drawCalls:R.info.render.calls,errors:[...state.errors],gesture:gesture?.kind||null,buffer:[canvas.width,canvas.height],postBuffer:[rt.width,rt.height],hdr:useHDR});
 C.editor={select,applyStyle,updateLightUI,addLight,applyLightFields,recordLighting,setTool,setTab,undo,redo,capture,applySnapshot,applyFields,exportProject,importProject,cameraSnapshot,restoreCamera,saveCamera,quality,exportPNG,updateProbe,renderNow,get selected(){return selected?.id||null},get historyLength(){return history.length}};
 C.__audit=()=>{root.updateMatrixWorld(true);const errors=[],b=new T.Box3().setFromObject(root);root.traverse(o=>{if(!o.matrixWorld.elements.every(Number.isFinite))errors.push(o.name+' matrix');if(o.isMesh&&!o.geometry.attributes.position.array.every(Number.isFinite))errors.push(o.name+' vertices');});return{errors,bounds:{min:b.min.toArray(),max:b.max.toArray()},cameraFinite:active.matrixWorld.elements.every(Number.isFinite),cameraTargetDistance:active.position.distanceTo(controls.target),rootIdentity:root.position.lengthSq()===0&&root.quaternion.equals(new T.Quaternion())};};
 C.measureScene=function(){root.updateMatrixWorld(true);return {rooms:C.rooms.map(r=>({id:r.id,area:r.area,point:r.point,bounds:r.bounds})),entities:entries.map(e=>{const b=C.localBounds(e.object),local=C.localBounds(e.object,e.object).getSize(new T.Vector3()).multiply(e.object.scale);return{size:local.toArray(),id:e.id,type:e.type,name:e.name,roomId:e.object.userData.roomId||null,componentId:e.object.userData.componentId||null,min:b.min.toArray(),max:b.max.toArray()};})};};
 function beyondNear(h,camera){return h.point.clone().applyMatrix4(camera.matrixWorldInverse).z<=-camera.near+.0001;}
 C.reviewShot=function(shot){const camera=new T.PerspectiveCamera(shot.fov,shot.frame.width/shot.frame.height,shot.near||.04,150);camera.position.fromArray(shot.position);camera.up.fromArray(shot.up);camera.lookAt(new T.Vector3(...shot.target));camera.updateMatrixWorld(true);root.updateMatrixWorld(true);
 const ray=new T.Raycaster(),results=[];for(const id of shot.subjectIds){const e=entityMap.get(id);if(!e)continue;const b=C.localBounds(e.object),points=[];for(const x of[b.min.x,(b.min.x+b.max.x)/2,b.max.x])for(const y of[b.min.y,(b.min.y+b.max.y)/2,b.max.y])for(const z of[b.min.z,(b.min.z+b.max.z)/2,b.max.z])points.push(new T.Vector3(x,y,z));let tested=0,clear=0;
 for(const point of points){const delta=point.clone().sub(camera.position),len=delta.length();ray.set(camera.position,delta.normalize());ray.far=len+.005;const hit=ray.intersectObject(root,true).find(h=>beyondNear(h,camera)&&isVisible(h.object)&&!h.object.userData.noExport&&!h.object.material?.transparent);if(!hit){clear++;tested++;continue;}let o=hit.object;while(o&&o!==root&&!o.userData.entityId)o=o.parent;if(o?.userData.entityId===id)clear++;tested++;}
 results.push({id,sampledClearRatio:clear/Math.max(tested,1),samples:tested});}return results;};
 C.framePlacementSamples=function(camera){
  root.updateMatrixWorld(true);camera.updateMatrixWorld(true);
  const ray=new T.Raycaster(),ids=[];
  for(const p of window.PROJECT.placements){
   const e=entityMap.get(p.id);if(!e||!isVisible(e.object))continue;
   const b=new T.Box3().setFromObject(e.object),corners=[];
   for(const x of[b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z])corners.push(new T.Vector3(x,y,z).applyMatrix4(camera.matrixWorldInverse));
   const near=-camera.near,clipped=corners.filter(q=>q.z<=near).map(q=>q.clone());
   for(let i=0;i<8;i++)for(const bit of[1,2,4]){const k=i^bit;if(k<=i)continue;const a=corners[i],c=corners[k];if((a.z<=near)!==(c.z<=near))clipped.push(a.clone().lerp(c,(near-a.z)/(c.z-a.z)));}
   if(!clipped.length)continue;
   const projected=clipped.map(q=>q.applyMatrix4(camera.projectionMatrix));
   const xmin=Math.max(-1,Math.min(...projected.map(q=>q.x))),xmax=Math.min(1,Math.max(...projected.map(q=>q.x))),ymin=Math.max(-1,Math.min(...projected.map(q=>q.y))),ymax=Math.min(1,Math.max(...projected.map(q=>q.y)));
   if(xmax<=xmin||ymax<=ymin)continue;
   let seen=false;
   // Sample the clipped image rectangle, not 3D box corners. A foreground
   // sliver can be visible even when every 3D sample falls outside the frame.
   for(const fx of[.08,.25,.5,.75,.92])for(const fy of[.08,.25,.5,.75,.92]){
    if(seen)continue;
    ray.setFromCamera(new T.Vector2(T.MathUtils.lerp(xmin,xmax,fx),T.MathUtils.lerp(ymin,ymax,fy)),camera);
    const hit=ray.intersectObject(root,true).find(h=>{if(!beyondNear(h,camera)||!isVisible(h.object)||h.object.userData.noExport)return false;const m=Array.isArray(h.object.material)?h.object.material[h.face?.materialIndex||0]:h.object.material;return m&&!m.transparent&&!(m.transmission>0);});
    let o=hit?.object;while(o&&o!==root&&!o.userData.entityId)o=o.parent;if(o?.userData.entityId===p.id)seen=true;
   }
   if(seen)ids.push(p.id);
  }
  return ids;
 };
 C.frameSpaceContext=function(camera,shot){
  root.updateMatrixWorld(true);camera.updateMatrixWorld(true);
  const P=window.PROJECT,rooms=new Map(P.rooms.map(r=>[r.id,{id:r.id,name:r.name,type:r.type}])),ray=new T.Raycaster(),seen=new Set(),portals=[];let floor=0,ceiling=0,total=0;
  const ancestors=(o,key)=>{while(o&&o!==root){if(o.userData[key]!==undefined)return o.userData[key];o=o.parent;}return null;};
  const opaque=h=>beyondNear(h,camera)&&isVisible(h.object)&&!h.object.userData.noExport&&!((Array.isArray(h.object.material)?h.object.material:[h.object.material]).every(m=>m.transparent||m.transmission>0));
  for(let y=0;y<19;y++)for(let x=0;x<25;x++){
   ray.setFromCamera(new T.Vector2(-1+2*(x+.5)/25,1-2*(y+.5)/19),camera);ray.far=Infinity;
   const hit=ray.intersectObject(root,true).find(opaque);total++;if(!hit)continue;
   const id=ancestors(hit.object,'roomId'),surface=ancestors(hit.object,'surfaceType');if(id&&rooms.has(id))seen.add(id);if(surface==='floor')floor++;if(surface==='ceiling')ceiling++;
  }
  const candidates=P.openings.map(o=>{const w=P.walls.find(w=>w.id===o.wallId),len=Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1]),u=[(w.b[0]-w.a[0])/len,(w.b[1]-w.a[1])/len];return {id:o.id,a:[w.a[0]+u[0]*o.offset,w.a[1]+u[1]*o.offset],b:[w.a[0]+u[0]*(o.offset+o.width),w.a[1]+u[1]*(o.offset+o.width)],bottom:o.sill,height:o.height,facts:window.OPENING_STATES[o.id]};});
  P.openConnections.forEach((c,i)=>candidates.push({id:'open-zone-'+i,a:c.span[0],b:c.span[1],bottom:0,height:P.floor.height,facts:{type:'open-zone',connects:c.rooms,state:'open',seeThrough:true,sourceStatus:'explicit',infill:'none'}}));
  for(const c of candidates){let visible=0;const projected=[];
   for(let j=0;j<5;j++)for(let i=0;i<5;i++){
    const u=(i+.5)/5,v=(j+.5)/5,p=new T.Vector3(c.a[0]+(c.b[0]-c.a[0])*u,c.bottom+c.height*v,c.a[1]+(c.b[1]-c.a[1])*u),ndc=p.clone().project(camera);
    if(ndc.z< -1||ndc.z>1||Math.abs(ndc.x)>1||Math.abs(ndc.y)>1)continue;
    const d=p.clone().sub(camera.position),distance=d.length();ray.set(camera.position,d.normalize());ray.far=Math.max(0,distance-.035);
    const blocked=ray.intersectObject(root,true).find(h=>opaque(h)&&ancestors(h.object,'openingId')!==c.id);if(blocked)continue;
    visible++;projected.push([(ndc.x+1)/2,(1-ndc.y)/2]);
   }
   if(!visible)continue;const f=c.facts,ends=(f.connects||[]).map(id=>id===null?{id:null,type:f.exteriorView?.kind||'unknown',description:f.exteriorView?.description||'外部目标未确认'}:rooms.get(id)||{id,type:'unknown'});
   portals.push({id:c.id,type:f.type,state:f.state,openFraction:f.openFraction??1,infill:f.infill,seeThrough:f.seeThrough,sourceStatus:f.sourceStatus,endpoints:ends,externalView:f.exteriorView||null,visibleApertureSamples:visible,imageSampleBounds01:[[Math.min(...projected.map(p=>p[0])),Math.min(...projected.map(p=>p[1]))],[Math.max(...projected.map(p=>p[0])),Math.max(...projected.map(p=>p[1]))]],connectionKnown:ends.length===2});
  }
  return {schema:'interior.frame-space/1',currentRoom:rooms.get(shot.roomId)||null,observedRooms:[...seen].map(id=>rooms.get(id)),portals,surfaceSamples:{total,floor,ceiling,floorFraction:floor/total,ceilingFraction:ceiling/total},method:'actual-camera-portal-and-surface-rays; sampled-evidence-not-pixel-proof',doorStateMode:'source',cameraRepresentation:shot.near?{kind:'virtual-axial-retreat',nearPlaneMetres:shot.near,geometryUnchanged:true}:{kind:'in-room'}};
 };
 C.captureFrame=async function(shot,mode='pbr',options={}){if(state.busy)throw Error('另一个截图任务尚未结束');const referenceMode=options.referenceMode||'furnished';if(!['furnished','empty-slots'].includes(referenceMode))throw Error('未知参考模式');if(referenceMode==='empty-slots'&&options.whiteModelRequested!==true)throw Error('空白槽位模式须由用户明确要求');const hiddenPlacementIds=[];const snap=cameraSnapshot(),before={roof:state.roof,cut:state.cut,wallVisible:state.wallVisible,furnitureVisible:state.furnitureVisible,doors:state.doors},ratio=R.getPixelRatio(),selection=helper?.visible,auto=state.auto;const originalVisible=new Map(entries.map(e=>[e.object,e.object.visible]));let savedMaterials;
 try{cancelGesture();state.auto=false;busy('正在按冻结机位出图…');state.wallVisible=state.furnitureVisible=true;state.roof=shot.visibility.ceiling;state.cut=shot.visibility.cutaway;entries.forEach(e=>e.object.visible=true);applyBuilding();ground.visible=shot.kind==='overview';
 active=shot.projection==='orthographic'?ortho:cam;controls.camera=active;active.position.fromArray(shot.position);active.up.fromArray(shot.up);controls.target.fromArray(shot.target);controls.lookAt();
 const w=shot.frame.width,h=shot.frame.height;R.setPixelRatio(1);R.setSize(w,h,false);rt.setSize(w,h);postMat.uniforms.resolution.value.set(w,h);if(active.isPerspectiveCamera){active.fov=shot.fov;active.near=shot.near||.04;active.aspect=w/h;active.zoom=1;active.setViewOffset(w,h,0,-(shot.verticalShift||0)*h/2,w,h);}else{const span=shot.orthographicSpan||12;active.top=span/2;active.bottom=-span/2;active.left=-span*w/h/2;active.right=span*w/h/2;active.zoom=1;}active.updateProjectionMatrix();if(helper)helper.visible=false;
 if(mode==='clay'){savedMaterials=new Map();const bySide=new Map();const neutral=original=>{if(original.transparent||original.transmission>0||original.alphaTest>0)return original;let m=bySide.get(original.side);if(!m){m=new T.MeshStandardMaterial({color:'#cbc6bc',roughness:.9,side:original.side});bySide.set(original.side,m);}return m;};root.traverse(o=>{if(o.isMesh&&!o.userData.noExport){savedMaterials.set(o,o.material);o.material=Array.isArray(o.material)?o.material.map(neutral):neutral(o.material);}});}
 if(referenceMode==='empty-slots'){for(const p of window.PROJECT.placements){const e=entityMap.get(p.id);if(!e||e.type!=='furniture')throw Error('槽位缺少对应可见家具：'+p.id);e.object.visible=false;hiddenPlacementIds.push(p.id);}}
 invalidate(true);draw();const dataUrl=canvas.toDataURL('image/png');const visiblePlacementIds=referenceMode==='furnished'?C.framePlacementSamples(active):null;return{dataUrl,width:w,height:h,sceneKey:window.SCENE_KEY,shotId:shot.id,referenceMode,hiddenPlacementIds,visiblePlacementIds,spaceContext:C.frameSpaceContext(active,shot),review:C.reviewShot(shot)};
 }finally{cam.clearViewOffset();if(savedMaterials)for(const[o,m]of savedMaterials)o.material=m;Object.assign(state,before);for(const[o,v]of originalVisible)o.visible=v;if(helper)helper.visible=selection;busy(null);restoreCamera(snap);layout(ratio);state.auto=auto;invalidate(true);}}
 try{const data=JSON.parse(localStorage.getItem('interior-cameras-'+window.PROJECT.id)||'[]');if(Array.isArray(data))savedCameras=data.filter(x=>typeof x.name==='string'&&validateCamera(x.camera)).slice(-20);}catch{}
 const observer=new ResizeObserver(()=>{if(!state.busy)layout();});observer.observe(stage);
 C.workspace=new C.Workspace({apply:applyWorkspace,importSnapshot:importProject,cancel:cancelGesture,toast});
 layout(Math.min(devicePixelRatio||1,1.35));refreshStyleUI();updateLightUI();refreshLists();refreshCameras();syncLightFields();lighting();setView('overview');setTab('style');draw();$('#engine').textContent='INTERIOR STUDIO 2.0.0 · OFFLINE';$('#loader').classList.add('done');if(document.querySelector('#saved-project')){await importProject(JSON.parse(document.querySelector('#saved-project').textContent));if(!document.querySelector('#saved-project').hasAttribute('data-compiled'))window.SCENE_KEY='edited-'+T.MathUtils.generateUUID();}window.__CREAM_READY__=true;
 function tick(now){requestAnimationFrame(tick);const dt=Math.min(.06,(now-lastTime)/1000);lastTime=now;if(state.auto&&!gesture&&!contextLost){controls.rotate(dt*5,0);dirty=true;}if(dirty)draw();}requestAnimationFrame(tick);
})(window.CREAM,window.THREE).catch(e=>{console.error(e);const el=document.getElementById('load-note');if(el)el.textContent='加载失败：'+e.message;});
