/* Editable physical sources, separate from furniture and from helper geometry.
 * Serializable values in metres / kelvin / candela. Rendering helpers never export. */
(function(C,T){'use strict';
 const clone=x=>JSON.parse(JSON.stringify(x));
 C.kelvinColor=function(k){const t=T.MathUtils.clamp(k,1800,8000)/100;let r=t<=66?255:329.698727446*Math.pow(t-60,-.1332047592),g=t<=66?99.4708025861*Math.log(t)-161.1195681661:288.1221695283*Math.pow(t-60,-.0755148492),b=t>=66?255:t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307;return new T.Color().setRGB(T.MathUtils.clamp(r/255,0,1),T.MathUtils.clamp(g/255,0,1),T.MathUtils.clamp(b/255,0,1),T.SRGBColorSpace);};
 C.validateLights=function(data){if(!Array.isArray(data)||data.length>24)throw Error('光源列表无效（最多24个）');const ids=new Set();for(const d of data){if(!d||typeof d.id!=='string'||!/^[a-zA-Z0-9_.-]{1,80}$/.test(d.id)||ids.has(d.id))throw Error('光源 ID 重复或无效');ids.add(d.id);if(!['point','spot'].includes(d.type)||typeof d.name!=='string'||d.name.length>80||typeof d.enabled!=='boolean'||typeof d.castShadow!=='boolean')throw Error('光源字段无效');for(const k of ['position','target'])if(!Array.isArray(d[k])||d[k].length!==3||!d[k].every(v=>Number.isFinite(v)&&Math.abs(v)<=50))throw Error('光源坐标无效');if(d.type==='spot'&&Math.hypot(...d.position.map((v,i)=>v-d.target[i]))<.05)throw Error('射灯目标不能与光源重合');for(const[k,min,max]of[['intensity',0,100],['temperature',1800,8000],['distance',.5,30],['angle',5,85],['penumbra',0,1]])if(!Number.isFinite(d[k])||d[k]<min||d[k]>max)throw Error('光源参数越界 '+k);if(d.type==='point'&&d.castShadow)throw Error('实时点光不启用六面阴影；请用射灯');if(d.anchorId!=null&&typeof d.anchorId!=='string')throw Error('光源绑定无效');if(d.anchorFraction!=null&&(!Number.isFinite(d.anchorFraction)||d.anchorFraction<0||d.anchorFraction>1))throw Error('灯具绑定高度无效');}
  if(data.filter(x=>x.enabled&&x.castShadow).length>3)throw Error('最多3个有阴影的射灯');return true;};
 C.LightRig=class{
  constructor(scene,records,invalidate){this.scene=scene;this.invalidate=invalidate;this.items=new Map();this.selected=null;this.helperRoot=new T.Group();this.helperRoot.name='光源编辑手柄（不导出）';this.helperRoot.userData.noExport=true;scene.add(this.helperRoot);this.enabled=false;this.suppressed=false;this.multiplier=1;this.day=true;this.restore(records);}
  serialize(){return[...this.items.values()].map(x=>clone(x.data));}
  get(id){return this.items.get(id);}
  make(data){const d=clone(data),light=d.type==='spot'?new T.SpotLight():new T.PointLight();light.name=d.name;light.decay=2;light.shadow.mapSize.set(512,512);light.shadow.normalBias=.02;light.shadow.bias=-.0001;light.userData.noExport=true;this.scene.add(light);if(light.isSpotLight)this.scene.add(light.target);
   const handle=new T.Group();handle.userData.lightId=d.id;const m=new T.MeshBasicMaterial({color:'#eacb88',depthTest:false,depthWrite:false,transparent:true,opacity:.90});const marker=new T.Mesh(new T.SphereGeometry(.10,12,8),m);marker.renderOrder=99;handle.add(marker);const ring=new T.Mesh(new T.TorusGeometry(.15,.012,5,32),m);ring.rotation.x=Math.PI/2;ring.renderOrder=100;handle.add(ring);this.helperRoot.add(handle);
   const rayGeo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]);const line=new T.Line(rayGeo,new T.LineBasicMaterial({color:'#dab574',depthTest:false,transparent:true,opacity:.6}));line.renderOrder=98;this.helperRoot.add(line);const entry={data:d,light,handle,marker,line};this.items.set(d.id,entry);this.apply(entry);return entry;}
  destroy(e){this.scene.remove(e.light);if(e.light.isSpotLight)this.scene.remove(e.light.target);e.light.shadow?.map?.dispose();e.light.dispose?.();this.helperRoot.remove(e.handle,e.line);const mats=new Set();e.handle.traverse(o=>{o.geometry?.dispose();if(o.material)mats.add(o.material);});mats.forEach(m=>m.dispose());e.line.geometry.dispose();e.line.material.dispose();}
  restore(records){C.validateLights(records);for(const e of this.items.values())this.destroy(e);this.items.clear();records.forEach(d=>this.make(d));if(!this.items.has(this.selected))this.selected=null;this.sync();}
  apply(e){const d=e.data,l=e.light;l.position.fromArray(d.position);l.color.copy(C.kelvinColor(d.temperature));l.intensity=d.intensity*this.multiplier*(this.day?.35:1);l.distance=d.distance;l.visible=d.enabled;l.castShadow=d.type==='spot'&&d.castShadow&&d.enabled;if(l.isSpotLight){l.target.position.fromArray(d.target);l.angle=T.MathUtils.degToRad(d.angle);l.penumbra=d.penumbra;l.target.updateMatrixWorld();}l.updateMatrixWorld();e.handle.position.fromArray(d.position);e.line.geometry.setFromPoints([new T.Vector3(...d.position),new T.Vector3(...d.target)]);e.line.visible=d.type==='spot'&&this.selected===d.id;e.marker.material.color.set(this.selected===d.id?'#ffffff':d.enabled?'#dab574':'#73777b');this.invalidate?.(true);}
  update(id,patch){const e=this.get(id);if(!e)throw Error('光源不存在');const next={...e.data,...clone(patch)};C.validateLights(this.serialize().map(d=>d.id===id?next:d));e.data=next;this.apply(e);}
  add(type,position,target,temperature=3000){let n=1;while(this.items.has('light-user-'+n))n++;const d={id:'light-user-'+n,name:type==='spot'?'新增射灯 '+n:'新增点光 '+n,type,position,target,intensity:type==='spot'?8:5,temperature,distance:8,angle:38,penumbra:.55,enabled:true,castShadow:false,anchorId:null,anchorFraction:.55};C.validateLights([...this.serialize(),d]);this.make(d);this.select(d.id);return d.id;}
  remove(id){const e=this.get(id);if(!e)return;this.destroy(e);this.items.delete(id);if(this.selected===id)this.selected=null;this.invalidate?.(true);}
  select(id){this.selected=this.items.has(id)?id:null;this.sync();}
  sync(){this.helperRoot.visible=this.enabled&&!this.suppressed;for(const e of this.items.values())this.apply(e);}
  lighting(multiplier,day){this.multiplier=multiplier;this.day=day;for(const e of this.items.values())this.apply(e);}
  show(on){this.enabled=on;this.helperRoot.visible=on&&!this.suppressed;}
  suppress(on){this.suppressed=on;this.helperRoot.visible=this.enabled&&!on;}
  pick(ray){if(!this.enabled||this.suppressed)return null;this.helperRoot.updateMatrixWorld(true);const hit=ray.intersectObject(this.helperRoot,true).find(h=>h.object.isMesh&&h.object.visible);let o=hit?.object;while(o&&!o.userData.lightId)o=o.parent;return o?this.get(o.userData.lightId):null;}
  scaleHandles(camera,height){for(const e of this.items.values()){const size=camera.isOrthographicCamera?(camera.top-camera.bottom)/camera.zoom/Math.max(1,height):2*e.handle.position.distanceTo(camera.position)*Math.tan(T.MathUtils.degToRad(camera.fov/2))/Math.max(1,height);e.handle.scale.setScalar(T.MathUtils.clamp(size*68,.7,2.2));}}
  move(id,position,detach=true){const e=this.get(id);if(!e)return;const delta=position.map((v,i)=>v-e.data.position[i]);this.update(id,{position,target:e.data.target.map((v,i)=>v+delta[i]),...(detach?{anchorId:null}:{})});}
 };
 C.defaultLights=function(project,rooms,style){const records=rooms.map((r,i)=>({id:'light-room-'+r.id,name:r.name+' · 柔光',type:'point',position:[r.point[0],project.floor.height-.24,r.point[2]],target:[r.point[0],0,r.point[2]],intensity:Math.min(6,Math.max(2,style.lighting.ambientIntensity*r.area/12)),temperature:style.lighting.temperature,distance:8,angle:38,penumbra:.65,enabled:true,castShadow:false,anchorId:null,anchorFraction:.55}));
  for(const p of project.placements.filter(p=>['lamp.pendant','lamp.floor','lamp.table'].includes(p.componentId))){if(records.length>=24)break;records.push({id:'light-fixture-'+p.id,name:p.name+' · 光源',type:p.componentId==='lamp.pendant'?'spot':'point',position:[p.position[0],p.position[1]+p.size[1]*.55,p.position[2]],target:[p.position[0],Math.max(0,p.position[1]-.9),p.position[2]],intensity:style.lighting.fixtureIntensity,temperature:style.lighting.temperature,distance:7,angle:42,penumbra:.65,enabled:true,castShadow:p.componentId==='lamp.pendant'&&records.filter(x=>x.castShadow).length<3,anchorId:p.id,anchorFraction:.55});}return records;};
})(window.CREAM,window.THREE);
