/* Embedded GLB 2 reader. Static TRIANGLES, PNG/JPEG/WebP and standard PBR only.
   No external URIs, eval, plugins, network requests or silently skipped compression. */
(function(C,T){'use strict';
 const records=new Map(),templates=new Map();
 function decode64(text){const s=atob(text),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a.buffer;}
 function encode64(buffer){const a=new Uint8Array(buffer);let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s);}
 function header(buffer){const v=new DataView(buffer);if(v.byteLength<28||v.getUint32(0,true)!==0x46546c67||v.getUint32(4,true)!==2||v.getUint32(8,true)!==buffer.byteLength)throw Error('不是完整 GLB 2 文件');let json=null,bin=null,p=12;while(p+8<=buffer.byteLength){const n=v.getUint32(p,true),type=v.getUint32(p+4,true);p+=8;if(p+n>buffer.byteLength)throw Error('GLB chunk 越界');if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,p,n)));if(type===0x004e4942)bin=buffer.slice(p,p+n);p+=n;}if(p!==buffer.byteLength||!json||!bin)throw Error('GLB JSON/BIN 不完整');return{json,bin};}
 function validateRecord(r){if(!r||!/^[-a-zA-Z0-9_.]{1,80}$/.test(r.id)||!r.name||!Array.isArray(r.size)||r.size.length!==3||r.size.some(x=>!Number.isFinite(x)||x<=0||x>30)||!['+Z','-Z','+X','-X'].includes(r.forward||'+Z')||!['uniform','axes'].includes(r.deform||'uniform')||typeof r.modelBase64!=='string'||r.modelBase64.length>90e6)throw Error('原生资产字段无效');header(decode64(r.modelBase64));return true;}
 async function parse(buffer){const {json:g,bin}=header(buffer);if(g.asset?.version!=='2.0')throw Error('只支持 glTF 2.0');if(g.buffers?.length!==1||g.buffers[0].uri)throw Error('GLB 必须自包含单一 BIN 缓冲');
  const supported=['KHR_texture_transform','KHR_materials_emissive_strength'];for(const x of g.extensionsRequired||[])if(!supported.includes(x))throw Error('需要离线预转换的GLB扩展：'+x);
  if(g.skins?.length||g.animations?.length)throw Error('家具导入使用静态烘焙网格；动画/骨骼请先烘焙');
  const component={5120:[Int8Array,1,'getInt8'],5121:[Uint8Array,1,'getUint8'],5122:[Int16Array,2,'getInt16'],5123:[Uint16Array,2,'getUint16'],5125:[Uint32Array,4,'getUint32'],5126:[Float32Array,4,'getFloat32']},width={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
  function accessor(i){const a=g.accessors?.[i],b=g.bufferViews?.[a?.bufferView];if(!a||!b||a.sparse||b.buffer!==0)throw Error('不支持 sparse 或无 BIN 的 accessor');if(b.extensions?.EXT_meshopt_compression)throw Error('Meshopt 资产请先离线解压');const spec=component[a.componentType],w=width[a.type];if(!spec||!w||!Number.isInteger(a.count)||a.count<0||a.count>8e6)throw Error('无效 accessor');const stride=b.byteStride||spec[1]*w,offset=(b.byteOffset||0)+(a.byteOffset||0),end=offset+Math.max(0,a.count-1)*stride+spec[1]*w;if(stride<spec[1]*w||end>bin.byteLength||end>(b.byteOffset||0)+b.byteLength)throw Error('GLB accessor 越界');const data=new spec[0](a.count*w),dv=new DataView(bin);for(let n=0;n<a.count;n++)for(let k=0;k<w;k++){const value=dv[spec[2]](offset+n*stride+k*spec[1],true);if(!Number.isFinite(value))throw Error('GLB 顶点非有限');data[n*w+k]=value;}return new T.BufferAttribute(data,w,!!a.normalized);}
  const images=await Promise.all((g.images||[]).map(async image=>{let blob;if(image.uri){if(!/^data:image\/(png|jpeg|webp);base64,/.test(image.uri))throw Error('不读取 GLB 外部图片 URI');const[type,b64]=image.uri.split(';base64,');blob=new Blob([decode64(b64)],{type:type.slice(5)});}else{const b=g.bufferViews?.[image.bufferView];if(!b||b.buffer!==0||!['image/png','image/jpeg','image/webp'].includes(image.mimeType))throw Error('GLB 图片格式不支持');blob=new Blob([bin.slice(b.byteOffset||0,(b.byteOffset||0)+b.byteLength)],{type:image.mimeType});}const url=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('GLB 图片解码失败'));im.src=url;});}finally{URL.revokeObjectURL(url);}}));
  function texture(info,color=false){if(!info)return null;const record=g.textures?.[info.index],im=images[record?.source];if(!im||info.texCoord>0||Object.keys(info.extensions||{}).some(x=>x!=='KHR_texture_transform'))throw Error('纹理引用/UV扩展不支持，先离线烘焙');const t=new T.Texture(im),sampler=g.samplers?.[record.sampler]||{};t.flipY=false;t.colorSpace=color?T.SRGBColorSpace:T.NoColorSpace;const wraps={10497:T.RepeatWrapping,33071:T.ClampToEdgeWrapping,33648:T.MirroredRepeatWrapping},filters={9728:T.NearestFilter,9729:T.LinearFilter,9984:T.NearestMipmapNearestFilter,9985:T.LinearMipmapNearestFilter,9986:T.NearestMipmapLinearFilter,9987:T.LinearMipmapLinearFilter};t.wrapS=wraps[sampler.wrapS??10497];t.wrapT=wraps[sampler.wrapT??10497];if(t.wrapS===undefined||t.wrapT===undefined)throw Error('GLB采样器wrap枚举无效');if(sampler.magFilter!==undefined){if(![9728,9729].includes(sampler.magFilter))throw Error('GLB magFilter无效');t.magFilter=filters[sampler.magFilter];}if(sampler.minFilter!==undefined){if(filters[sampler.minFilter]===undefined)throw Error('GLB minFilter无效');t.minFilter=filters[sampler.minFilter];}const xf=info.extensions?.KHR_texture_transform;if(xf){if(xf.texCoord>0)throw Error('只支持UV0');for(const k of ['offset','scale'])if(xf[k]&&(!Array.isArray(xf[k])||xf[k].length!==2||!xf[k].every(Number.isFinite)))throw Error('纹理坐标变换无效');if(xf.rotation!==undefined&&!Number.isFinite(xf.rotation))throw Error('纹理旋转无效');if(xf.offset)t.offset.fromArray(xf.offset);if(xf.scale)t.repeat.fromArray(xf.scale);t.rotation=xf.rotation||0;}t.needsUpdate=true;return t;}
  const mats=(g.materials||[{}]).map((m,i)=>{const p=m.pbrMetallicRoughness||{},col=p.baseColorFactor||[1,1,1,1],mat=new T.MeshStandardMaterial({name:m.name||'material-'+i,color:new T.Color().setRGB(...col.slice(0,3)),roughness:p.roughnessFactor??1,metalness:p.metallicFactor??0,opacity:col[3]??1,transparent:m.alphaMode==='BLEND',alphaTest:m.alphaMode==='MASK'?(m.alphaCutoff??.5):0,side:m.doubleSided?T.DoubleSide:T.FrontSide});mat.map=texture(p.baseColorTexture,true);mat.normalMap=texture(m.normalTexture);if(mat.normalMap)mat.normalScale.setScalar(m.normalTexture.scale??1);mat.roughnessMap=mat.metalnessMap=texture(p.metallicRoughnessTexture);mat.emissive.setRGB(...(m.emissiveFactor||[0,0,0]));mat.emissiveIntensity=m.extensions?.KHR_materials_emissive_strength?.emissiveStrength??1;mat.emissiveMap=texture(m.emissiveTexture,true);mat.userData.nativeMaterial=true;return mat;});
  function mesh(id){const source=g.meshes?.[id];if(!source)throw Error('mesh 引用无效');const group=new T.Group();group.name=source.name||'mesh';for(const p of source.primitives){if((p.mode??4)!==4||p.targets||p.extensions?.KHR_draco_mesh_compression)throw Error('仅支持未压缩静态三角面，先离线转换资产');const geo=new T.BufferGeometry();for(const [key,index]of Object.entries(p.attributes)){const name={POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv',COLOR_0:'color',TANGENT:'tangent'}[key];if(name)geo.setAttribute(name,accessor(index));}if(!geo.attributes.position)throw Error('网格缺 POSITION');if(p.indices!==undefined){const ix=accessor(p.indices);if(ix.itemSize!==1||Array.from(ix.array).some(v=>v<0||v>=geo.attributes.position.count))throw Error('索引越界');geo.setIndex(ix);}if(!geo.attributes.normal)geo.computeVertexNormals();geo.computeBoundingBox();geo.computeBoundingSphere();const material=mats[p.material??0];if(!material)throw Error('材质索引越界');const o=new T.Mesh(geo,material);o.castShadow=o.receiveShadow=true;group.add(o);}return group;}
  const visiting=new Set();function node(i,depth=0){const n=g.nodes?.[i];if(!n||depth>64||visiting.has(i))throw Error('GLB 节点树无效');visiting.add(i);const o=n.mesh!==undefined?mesh(n.mesh):new T.Group();o.name=n.name||o.name;if(n.matrix){if(n.matrix.length!==16||!n.matrix.every(Number.isFinite))throw Error('GLB matrix无效');o.matrix.fromArray(n.matrix);o.matrix.decompose(o.position,o.quaternion,o.scale);}else{if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);}if(![...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()].every(Number.isFinite))throw Error('GLB transform无效');for(const child of n.children||[])o.add(node(child,depth+1));visiting.delete(i);return o;}
  const root=new T.Group(),scene=g.scenes?.[g.scene??0];if(!scene)throw Error('GLB 缺少 scene');for(const id of scene.nodes||[])root.add(node(id));root.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(root);if(bounds.isEmpty())throw Error('GLB 没有可绘制网格');return root;
 }
 async function prepare(input){for(const r of input){validateRecord(r);const prev=records.get(r.id);if(prev&&prev.modelBase64===r.modelBase64&&(prev.forward||'+Z')===(r.forward||'+Z')&&JSON.stringify(prev.size)===JSON.stringify(r.size))continue;const model=await parse(decode64(r.modelBase64));const orient=new T.Group();orient.rotation.y={'+Z':0,'-Z':Math.PI,'+X':-Math.PI/2,'-X':Math.PI/2}[r.forward||'+Z'];orient.add(model);orient.updateMatrixWorld(true);const b=new T.Box3().setFromObject(orient),size=b.getSize(new T.Vector3());if(Math.min(...size.toArray())<.001)throw Error('GLB 三维包络退化');const center=b.getCenter(new T.Vector3()),normalized=new T.Group();orient.position.set(-center.x,-b.min.y,-center.z);normalized.add(orient);normalized.userData.measuredSize=size.toArray();records.set(r.id,structuredClone(r));templates.set(r.id,normalized);}}
 function create(parent,p){const r=records.get(p.nativeAssetId),src=templates.get(p.nativeAssetId);if(!r||!src)throw Error('缺少原生资产 '+p.nativeAssetId);const dims=src.userData.measuredSize,ratio=p.size.map((v,i)=>v/r.size[i]);if((r.deform||'uniform')==='uniform'&&Math.max(...ratio)-Math.min(...ratio)>.002)throw Error('该资产仅允许等比缩放，不能压扁五金');const o=C.group(parent,p.name,...p.position,T.MathUtils.degToRad(p.rotationY)),body=src.clone(true);body.scale.set(...p.size.map((v,i)=>v/dims[i]));body.traverse(m=>{if(!m.isMesh)return;const old=Array.isArray(m.material)?m.material:[m.material];const next=old.map(mat=>{const x=mat.clone(),patch=p.materialOverrides?.[mat.name];if(patch?.color)x.color.set(patch.color);if(Number.isFinite(patch?.roughness))x.roughness=patch.roughness;if(Number.isFinite(patch?.metalness))x.metalness=patch.metalness;return x;});m.material=Array.isArray(m.material)?next:next[0];});o.add(body);Object.assign(o.userData,{semantic:p.name,sourceId:p.id,roomId:p.roomId,componentId:p.componentId,nativeAssetId:p.nativeAssetId});C.assets.push(o);return o;}
 C.nativeAssets={prepare,create,parse,validateRecord,decode64,encode64,records};
})(window.CREAM,window.THREE);
