/* The same deterministic spatial kernel is used in browser edits and Node-backed CLI checks.
   Layout facts are never silently repaired. Envelope warnings are not exact mesh collision. */
(function(host){'use strict';
 const finite=(a,n)=>Array.isArray(a)&&a.length===n&&a.every(v=>typeof v==='number'&&Number.isFinite(v));
 function area(poly){return Math.abs(poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+p[0]*q[1]-p[1]*q[0];},0))/2;}
 function segment(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1)));return[a[0]+dx*t,a[1]+dy*t];}
 function inside(p,poly,tolerance=.002){if(poly.some((a,i)=>{const s=segment(p,a,poly[(i+1)%poly.length]);return Math.hypot(p[0]-s[0],p[1]-s[1])<=tolerance;}))return true;let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
 function polygon(p,local){const a=p.rotationY*Math.PI/180,c=Math.cos(a),s=Math.sin(a),shape=local||[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]];return shape.map(([u,v])=>[p.position[0]+c*u*p.size[0]+s*v*p.size[2],p.position[2]-s*u*p.size[0]+c*v*p.size[2]]);}
 function intersects(a,b,epsilon=.008){for(const poly of[a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],nx=-(q[1]-p[1]),ny=q[0]-p[0],len=Math.hypot(nx,ny);if(len<1e-8)continue;const aa=a.map(v=>(v[0]*nx+v[1]*ny)/len),bb=b.map(v=>(v[0]*nx+v[1]*ny)/len);if(Math.min(Math.max(...aa),Math.max(...bb))-Math.max(Math.min(...aa),Math.min(...bb))<=epsilon)return false;}return true;}
 function wallParts(layout,w,y0,y1){const dx=w.b[0]-w.a[0],dz=w.b[1]-w.a[1],len=Math.hypot(dx,dz),ops=layout.openings.filter(o=>o.wallId===w.id&&o.sill<=y0+.005&&o.sill+o.height>=y1-.005).sort((a,b)=>a.offset-b.offset),spans=[];let from=0;for(const o of ops){if(o.offset>from)spans.push([from,o.offset]);from=Math.max(from,o.offset+o.width);}if(from<len)spans.push([from,len]);return spans.map(([a,b])=>{const p={position:[w.a[0]+dx*(a+b)/2/len,0,w.a[1]+dz*(a+b)/2/len],rotationY:-Math.atan2(dz,dx)*180/Math.PI,size:[b-a,w.height,w.thickness]};return polygon(p);});}
 function validateStructure(l){const errors=[],ids=new Set();if(!l||l.schema!=='interior.layout/1')return['schema 必须是 interior.layout/1'];for(const k of['walls','rooms','placements','openings']){if(!Array.isArray(l[k]))return[k+' 缺失'];for(const x of l[k]){if(!x.id||ids.has(x.id))errors.push('对象ID重复/缺失 '+x.id);ids.add(x.id);}}if(!l.floor?.outline?.every(p=>finite(p,2))||area(l.floor.outline)<.01)return['楼面多边形无效'];
  for(const w of l.walls){if(!finite(w.a,2)||!finite(w.b,2)||Math.hypot(w.a[0]-w.b[0],w.a[1]-w.b[1])<.02||!(w.thickness>0&&w.thickness<2)||!(w.height>0&&w.height<=l.floor.height+.001))errors.push('墙体几何无效 '+w.id);}
  const intervals={};for(const o of l.openings){const w=l.walls.find(w=>w.id===o.wallId);if(!w){errors.push('宿主墙不存在 '+o.id);continue;}if(![o.offset,o.width,o.height,o.sill].every(Number.isFinite)||o.offset<0||o.width<=0||o.height<=0||o.sill<0||o.offset+o.width>Math.hypot(w.a[0]-w.b[0],w.a[1]-w.b[1])+.001||o.sill+o.height>w.height+.001)errors.push('门窗超出宿主墙 '+o.id);if(['window','fixed-glazing'].includes(o.type)&&o.connects)errors.push('窗不能当通行门 '+o.id);for(const a of intervals[w.id]||[])if(Math.min(a.offset+a.width,o.offset+o.width)-Math.max(a.offset,o.offset)>.002)errors.push('同宿主重叠门窗 '+o.id);(intervals[w.id]||=[]).push(o);}
  for(const p of l.placements)if(!finite(p.position,3)||!finite(p.size,3)||p.size.some(v=>v<=0||v>30)||!Number.isFinite(p.rotationY)||!l.rooms.some(r=>r.id===p.roomId))errors.push('家具尺寸/房间无效 '+p.id);return errors;
 }
 function audit(l,id){const p=l.placements.find(x=>x.id===id);if(!p)return{errors:['missing-placement'],warnings:[]};const asset=(l.nativeAssets||[]).find(a=>a.id===p.nativeAssetId),shape=polygon(p,asset?.footprint),errors=[],warnings=[],y0=p.position[1],y1=y0+p.size[1];
  if(!shape.every(q=>inside(q,l.floor.outline))||shape.some((a,i)=>{const b=shape[(i+1)%shape.length];return[.25,.5,.75].some(t=>!inside([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t],l.floor.outline));}))errors.push('outside-floor');if(y0<-.05||y1>l.floor.height+.02)errors.push('outside-height');
  const excluded=/rug|curtain|art|pendant|lamp/;if(!excluded.test(p.componentId)){for(const w of l.walls){if(y0>=w.height-.005)continue;if(wallParts(l,w,y0,Math.min(y1,w.height)).some(poly=>intersects(shape,poly)))warnings.push('wall:'+w.id);}for(const q of l.placements){if(q.id===id||excluded.test(q.componentId))continue;if(Math.min(y1,q.position[1]+q.size[1])-Math.max(y0,q.position[1])<.08)continue;const other=(l.nativeAssets||[]).find(a=>a.id===q.nativeAssetId);if(intersects(shape,polygon(q,other?.footprint),.03))warnings.push('furniture:'+q.id);}
   for(const o of l.openings.filter(o=>['door','sliding-door','passage'].includes(o.type))){const w=l.walls.find(x=>x.id===o.wallId);if(!w||y0>.25)continue;const d=Math.hypot(w.a[0]-w.b[0],w.a[1]-w.b[1]),t=(o.offset+o.width/2)/d,clear={position:[w.a[0]+(w.b[0]-w.a[0])*t,0,w.a[1]+(w.b[1]-w.a[1])*t],size:[o.width,1,.65],rotationY:-Math.atan2(w.b[1]-w.a[1],w.b[0]-w.a[0])*180/Math.PI};if(intersects(shape,polygon(clear)))warnings.push('door-clearance:'+o.id);}}
  return{errors,warnings:[...new Set(warnings)],footprint:shape,source:asset?.footprint?'asset-normalized-footprint':'component-envelope'};
 }
 const api={area,inside,segment,polygon,intersects,validateStructure,audit};if(typeof module==='object'&&module.exports)module.exports=api;else host.Spatial=api;
})(typeof window!=='undefined'?window:globalThis);
