/* Workspace tools use editor facade transactions, never duplicate furniture/camera state. */
(function(C,T){'use strict';
 C.Workspace=class{
  constructor(api){this.api=api;this.measuring=false;this.first=null;this.endpoint=null;this.library=[];this.unit=window.PROJECT.measurementUnit||'m';this.lines=new T.Group();this.lines.name='编辑尺规（不导出）';this.lines.userData.noExport=true;C.scene.add(this.lines);this.install();this.refresh();}
  install(){const $=s=>document.querySelector(s);this.$=$;
   const footer=$('.studio-footer');footer.insertAdjacentHTML('afterbegin','<div class="pro-actions"><button id="save-html" class="primary">保存完整 HTML</button><button id="import-html">打开已编辑 HTML</button></div><input id="html-input" type="file" accept=".html" hidden>');
   const walls=$('[data-panel="walls"]');walls.insertAdjacentHTML('beforeend',`<details id="structure-tools"><summary>墙端 / 门窗编辑</summary><p class="pro-hint">先解锁墙体。结构修改只更新同一布局；房间边界需在平面页同步核对，不自动臆造。</p><label>墙体<select id="edit-wall"></select></label><div class="number-grid"><label>A · X<input id="wall-ax" type="number" step=".05"></label><label>A · Z<input id="wall-az" type="number" step=".05"></label><label>B · X<input id="wall-bx" type="number" step=".05"></label><label>B · Z<input id="wall-bz" type="number" step=".05"></label><label>厚度 m<input id="wall-thickness" type="number" step=".01"></label><label>高度 m<input id="wall-height" type="number" step=".05"></label></div><div class="pro-actions"><button id="wall-apply">应用墙体</button><button id="wall-add">新增墙体</button><button id="wall-delete">删除墙体</button><button id="wall-drag">拖端点</button></div><p id="structure-note" class="pro-hint"></p><label>门窗<select id="edit-opening"></select></label><div class="number-grid"><label>墙上偏移 m<input id="opening-offset" type="number" step=".05"></label><label>宽度 m<input id="opening-width" type="number" step=".05"></label><label>窗台 m<input id="opening-sill" type="number" step=".05"></label><label>高度 m<input id="opening-height" type="number" step=".05"></label><label>类型<select id="opening-type"><option value="door">平开门</option><option value="sliding-door">移门</option><option value="passage">通道</option><option value="window">窗</option><option value="fixed-glazing">固定玻璃</option></select></label></div><div class="pro-actions"><button id="opening-apply">应用门窗</button><button id="opening-add">新增开口</button><button id="opening-delete">删除开口</button></div></details>`);
   $('[data-panel="camera"]').insertAdjacentHTML('beforeend',`<details open><summary>比例尺 / 面积 / 拉尺</summary><p id="area-summary" class="pro-hint"></p><div class="pro-actions"><button id="measure-start">两点拉尺</button><button id="measure-cancel">取消</button></div><div class="pro-row">单位<select id="measure-unit"><option value="m">米</option><option value="mm">毫米</option></select></div><p class="pro-hint">二维/三维都投影到世界地板平面 Y=0。吸附墙端/家具包络边，不把屏幕像素当距离。边界面积不扣墙柱，不是产权面积。</p><div id="measurement-list" class="object-list"></div><button id="measure-clear">清除量尺</button></details>`);
   $('#stage').insertAdjacentHTML('beforeend','<div id="scale-hud"><span id="scale-label"></span><i id="scale-bar"></i><small id="scale-note"></small></div><div id="measure-overlay"></div>');
   document.body.insertAdjacentHTML('beforeend',`<section id="furniture-library" hidden><div class="library-head"><b>本地家具库</b><input id="library-search" placeholder="名称 / 类别 / 风格"><label>宽度上限 m <input id="library-max-width" type="number" min="0" step=".1" placeholder="不限"></label><select id="library-room"></select><button id="load-library">选择模型目录</button><button id="close-library">收起</button><input id="library-folder" type="file" webkitdirectory directory multiple hidden></div><p class="pro-hint" id="library-message">授权选择含 library.json 与 GLB 的目录。只将本项目使用的资产嵌入交付 HTML，不读取任意磁盘路径。</p><div id="library-items"></div></section>`);
   $('[data-panel="furniture"]').insertAdjacentHTML('afterbegin','<button id="show-library" class="primary" style="width:100%;margin-bottom:10px">打开底部家具库 / 替换款式</button>');
   $('#object-editor').insertAdjacentHTML('beforeend','<details><summary>材质槽 / 原生尺寸 / 删除</summary><select id="native-slot"></select><div class="number-grid"><label>颜色<input id="slot-color" type="color" value="#c2ad94"></label><label>粗糙度<input id="slot-roughness" type="number" min="0" max="1" step=".05" value=".7"></label><label>金属度<input id="slot-metalness" type="number" min="0" max="1" step=".05" value="0"></label></div><div class="pro-actions"><button id="apply-slot">应用材质槽</button><button id="remove-placement">删除家具</button></div><p class="pro-hint">原生家具按资产标注决定等比/分轴变形；更换款式默认使用真实尺寸，不自动压扁。</p></details>');
   const style=$('[data-panel="style"]');style.insertAdjacentHTML('beforeend','<details><summary>其它风格（联网研究入口）</summary><input id="style-query" class="search" placeholder="例如：地中海 × 当代简约 70/30"><button id="style-research">导出风格研究任务</button><p class="pro-hint">浏览器不会代用账号联网。Agent 根据任务真实检索，再导入完整配方；失败明确记录，不能退回奶油风。</p></details>');
   $('#save-html').onclick=()=>this.saveHTML();$('#import-html').onclick=()=>$('#html-input').click();$('#html-input').onchange=e=>this.safe(async()=>{const file=e.target.files[0];if(file){const parser=new DOMParser(),d=parser.parseFromString(await file.text(),'text/html'),node=d.querySelector('#saved-project');if(!node)throw Error('此HTML没有可恢复的完整编辑快照；不能执行陌生脚本');await this.api.importSnapshot(JSON.parse(node.textContent));this.refresh();}e.target.value='';});
   $('#show-library').onclick=()=>{$('#furniture-library').hidden=false;document.body.classList.add('library-open');C.layout();this.renderLibrary();};$('#close-library').onclick=()=>{$('#furniture-library').hidden=true;document.body.classList.remove('library-open');C.layout();};$('#load-library').onclick=()=>$('#library-folder').click();$('#library-folder').onchange=e=>this.safe(()=>this.loadLibrary([...e.target.files]));$('#library-search').oninput=()=>this.renderLibrary();$('#library-max-width').oninput=()=>this.renderLibrary();
   $('#edit-wall').onchange=()=>this.fillWall();$('#edit-opening').onchange=()=>this.fillOpening();$('#wall-apply').onclick=()=>this.safe(()=>this.editWall());$('#wall-add').onclick=()=>this.safe(()=>this.addWall());$('#wall-delete').onclick=()=>this.safe(()=>this.deleteWall());$('#wall-drag').onclick=()=>{if(C.state.wallLocked)return this.api.toast('请先解锁墙体');C.setView('plan');this.endpoint={id:$('#edit-wall').value,active:true};$('#structure-note').textContent='在平面上拖所选墙的任一端点；按 Esc 取消。';};
   $('#opening-apply').onclick=()=>this.safe(()=>this.editOpening());$('#opening-add').onclick=()=>this.safe(()=>this.addOpening());$('#opening-delete').onclick=()=>this.safe(()=>this.deleteOpening());
   $('#measure-start').onclick=()=>{this.api.cancel();this.measuring=true;this.first=null;this.api.toast('点击地板平面上的两个点，吸附墙端与家具边');};$('#measure-cancel').onclick=()=>this.cancel();$('#measure-clear').onclick=()=>this.safe(async()=>{const p=C.exportLayout(false);p.measurements=[];await this.api.apply(p);this.refresh();});$('#measure-unit').value=this.unit;$('#measure-unit').onchange=e=>{this.unit=e.target.value;window.PROJECT.measurementUnit=this.unit;this.refreshMeasurements();};
   $('#apply-slot').onclick=()=>this.safe(()=>this.material());$('#remove-placement').onclick=()=>this.safe(()=>this.remove());$('#style-research').onclick=()=>{const query=$('#style-query').value.trim();if(!query)return;this.downloadJSON({schema:'interior.style-research/1',query,status:'research-required',sources:[],extract:['palette','materials','forms','details','lighting','componentBindings'],note:'由当前Agent真实联网检索；不自动申请付费资产。'},'style-research.json');};
   const canvas=$('#webgl');canvas.addEventListener('pointerdown',e=>{if(C.state.busy||e.button!==0)return;if(this.measuring){e.stopImmediatePropagation();e.preventDefault();const p=this.groundPoint(e.clientX,e.clientY);if(!p)return;const snap=this.snap(p);if(!this.first){this.first=snap;this.api.toast('已选第一点，继续选第二点');}else{const a=this.first,b=snap;if(a.distanceTo(b)<.005)return;this.measuring=false;this.first=null;this.safe(async()=>{const data=C.exportLayout(false);(data.measurements||=[]).push({id:'measure-'+T.MathUtils.generateUUID().slice(0,8),a:a.toArray(),b:b.toArray(),plane:'Y=0'});await this.api.apply(data);this.refresh();});}}else if(this.endpoint?.active&&C.state.tab==='walls'&&!C.state.wallLocked){const w=window.PROJECT.walls.find(w=>w.id===this.endpoint.id),p=this.groundPoint(e.clientX,e.clientY);if(!w||!p)return;let key=null;for(const k of['a','b'])if(Math.hypot(w[k][0]-p.x,w[k][1]-p.z)<.35)key=k;if(key){e.stopImmediatePropagation();e.preventDefault();canvas.setPointerCapture(e.pointerId);this.endpoint={...this.endpoint,key,pointerId:e.pointerId,before:C.exportLayout(false),candidate:p};}}},true);
   canvas.addEventListener('pointermove',e=>{if(this.endpoint?.key&&e.pointerId===this.endpoint.pointerId){e.stopImmediatePropagation();const p=this.groundPoint(e.clientX,e.clientY);if(p){this.endpoint.candidate=p;$('#structure-note').textContent=`候选 ${p.x.toFixed(2)}, ${p.z.toFixed(2)} m；松手应用。`;}}},true);
   canvas.addEventListener('pointerup',e=>{if(this.endpoint?.key&&e.pointerId===this.endpoint.pointerId){e.stopImmediatePropagation();const g=this.endpoint;this.endpoint=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);this.safe(async()=>{const w=g.before.walls.find(w=>w.id===g.id);w[g.key]=[g.candidate.x,g.candidate.z];await this.api.apply(g.before);this.refresh();});}},true);
   canvas.addEventListener('pointercancel',()=>this.cancel(),true);window.addEventListener('keydown',e=>{if(e.key==='Escape')this.cancel();},true);
  }
  safe(fn){return Promise.resolve().then(fn).catch(e=>this.api.toast(e.message));}
  cancel(){this.measuring=false;this.first=null;this.endpoint=null;}
  groundPoint(x,y){const camera=C.getActiveCamera(),r=this.$('#webgl').getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),camera);return ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),0),new T.Vector3());}
  snap(v){const P=C.exportLayout(false),points=P.walls.flatMap(w=>[w.a,w.b]);for(const p of P.placements){const poly=Spatial.polygon(p);for(let i=0;i<poly.length;i++){points.push(poly[i]);points.push(Spatial.segment([v.x,v.z],poly[i],poly[(i+1)%poly.length]));}}let best=v.clone(),d=.12;for(const p of points){const delta=Math.hypot(v.x-p[0],v.z-p[1]);if(delta<d){best.set(p[0],0,p[1]);d=delta;}}return best;}
  refresh(){const $=this.$,p=window.PROJECT,wallId=$('#edit-wall').value,openingId=$('#edit-opening').value;$('#edit-wall').replaceChildren(...p.walls.map(w=>new Option(w.name,w.id)));if(p.walls.some(w=>w.id===wallId))$('#edit-wall').value=wallId;$('#edit-opening').replaceChildren(...p.openings.map(o=>new Option(o.id+' · '+o.type,o.id)));if(p.openings.some(o=>o.id===openingId))$('#edit-opening').value=openingId;$('#library-room').replaceChildren(...p.rooms.map(r=>new Option(r.name,r.id)));this.fillWall();this.fillOpening();$('#area-summary').textContent='楼面边界面积 '+Spatial.area(p.floor.outline).toFixed(2)+' m²。'+p.rooms.map(r=>r.name+' '+Spatial.area(r.polygon).toFixed(2)+' m²').join('；');this.refreshMeasurements();this.renderLibrary();}
  selectedChanged(){const e=C.entities.find(e=>e.id===C.editor.selected),select=this.$('#native-slot');select.replaceChildren();if(e){const names=new Set();e.object.traverse(o=>{for(const m of o.material?Array.isArray(o.material)?o.material:[o.material]:[])names.add(m.name||'unnamed');});for(const name of names)select.add(new Option(name,name));}}
  fillWall(){const w=window.PROJECT.walls.find(w=>w.id===this.$('#edit-wall').value);if(!w)return;for(const[k,v]of Object.entries({'wall-ax':w.a[0],'wall-az':w.a[1],'wall-bx':w.b[0],'wall-bz':w.b[1],'wall-thickness':w.thickness,'wall-height':w.height}))this.$('#'+k).value=v;}
  fillOpening(){const o=window.PROJECT.openings.find(o=>o.id===this.$('#edit-opening').value);if(!o)return;for(const k of['offset','width','sill','height','type'])this.$('#opening-'+k).value=o[k];}
  unlock(){if(C.state.wallLocked)throw Error('结构层已锁定，请先解锁');}
  async editWall(){this.unlock();const p=C.exportLayout(false),w=p.walls.find(w=>w.id===this.$('#edit-wall').value);if(!w)throw Error('先选墙');w.a=['ax','az'].map(k=>+this.$('#wall-'+k).value);w.b=['bx','bz'].map(k=>+this.$('#wall-'+k).value);w.thickness=+this.$('#wall-thickness').value;w.height=+this.$('#wall-height').value;await this.api.apply(p);this.refresh();}
  async addWall(){this.unlock();const p=C.exportLayout(false),v=C.controls.target,id='wall-'+T.MathUtils.generateUUID().slice(0,8);p.walls.push({id,name:'新增隔墙',a:[v.x-.5,v.z],b:[v.x+.5,v.z],thickness:.12,height:p.floor.height,kind:'wall'});await this.api.apply(p);this.refresh();this.$('#edit-wall').value=id;this.fillWall();}
  async deleteWall(){this.unlock();const p=C.exportLayout(false),id=this.$('#edit-wall').value;if(p.openings.some(o=>o.wallId===id))throw Error('此墙含门窗，先明确删除/迁移开口再删墙');p.walls=p.walls.filter(w=>w.id!==id);for(const r of p.rooms)if(r.frontWallId===id)delete r.frontWallId;await this.api.apply(p);this.refresh();}
  async editOpening(){this.unlock();const p=C.exportLayout(false),o=p.openings.find(o=>o.id===this.$('#edit-opening').value);if(!o)throw Error('先选门窗');for(const k of['offset','width','sill','height'])o[k]=+this.$('#opening-'+k).value;o.type=this.$('#opening-type').value;if(['window','fixed-glazing'].includes(o.type))delete o.connects;await this.api.apply(p);this.refresh();}
  async addOpening(){this.unlock();const p=C.exportLayout(false),w=p.walls.find(w=>w.id===this.$('#edit-wall').value);if(!w)throw Error('先选宿主墙');const id='opening-'+T.MathUtils.generateUUID().slice(0,8);p.openings.push({id,wallId:w.id,type:'door',offset:.1,width:.8,height:Math.min(2.1,w.height),sill:0});await this.api.apply(p);this.refresh();this.$('#edit-opening').value=id;this.fillOpening();}
  async deleteOpening(){this.unlock();const p=C.exportLayout(false);p.openings=p.openings.filter(o=>o.id!==this.$('#edit-opening').value);await this.api.apply(p);this.refresh();}
  format(m){return this.unit==='mm'?(m*1000).toFixed(0)+' mm':m.toFixed(3)+' m';}
  refreshMeasurements(){const $=this.$;this.lines.children.forEach(o=>{o.geometry?.dispose();o.material?.dispose();});this.lines.clear();$('#measurement-list').replaceChildren();for(const m of window.PROJECT.measurements||[]){const a=new T.Vector3(...m.a),b=new T.Vector3(...m.b),line=new T.Line(new T.BufferGeometry().setFromPoints([a.clone().setY(.03),b.clone().setY(.03)]),new T.LineBasicMaterial({color:0xf3b45c,depthTest:false}));line.userData.noExport=true;line.renderOrder=100;this.lines.add(line);const row=document.createElement('div');row.className='object-row';const span=document.createElement('span');span.textContent=this.format(a.distanceTo(b))+' · 地板Y=0';const btn=document.createElement('button');btn.textContent='×';btn.onclick=()=>this.safe(async()=>{const p=C.exportLayout(false);p.measurements=p.measurements.filter(x=>x.id!==m.id);await this.api.apply(p);this.refresh();});row.append(span,btn);$('#measurement-list').append(row);}}
  onFrame(){const $=this.$,camera=C.getActiveCamera(),h=$('#stage').clientHeight,pixelWorld=camera.isOrthographicCamera?(camera.top-camera.bottom)/camera.zoom/h:2*camera.position.distanceTo(C.controls.target)*Math.tan(camera.fov*Math.PI/360)/h;const target=pixelWorld*110,pow=10**Math.floor(Math.log10(Math.max(.001,target))),m=[1,2,5,10].map(x=>x*pow).find(x=>x>=target)||pow*10;$('#scale-bar').style.width=(m/pixelWorld)+'px';$('#scale-label').textContent=this.format(m);$('#scale-note').textContent=camera.isOrthographicCamera?'正交米制比例尺':'视图中心参考比例；拉尺在Y=0地板上';this.lines.visible=!C.state.busy;$('#scale-hud').style.display=C.state.busy?'none':'block';}
  async loadLibrary(files){const paths=new Map(files.map(f=>[f.webkitRelativePath||f.name,f])),index=files.find(f=>f.name==='library.json');if(!index)throw Error('目录中缺少 library.json');const info=JSON.parse(await index.text());if(info.schema!=='interior.asset-library/1'||!Array.isArray(info.items))throw Error('家具目录格式无效');const prefix=(index.webkitRelativePath||index.name).slice(0,-index.name.length),loaded=[];for(const item of info.items){if(item.modelPath?.includes('..')||/^([a-z]:|\/|https?:)/i.test(item.modelPath||''))throw Error('模型只能引用授权目录内的相对路径');const f=paths.get(prefix+item.modelPath);if(!f)throw Error('缺少模型文件 '+item.modelPath);const asset={...item,modelBase64:C.nativeAssets.encode64(await f.arrayBuffer())};delete asset.modelPath;delete asset.thumbnail;C.nativeAssets.validateRecord(asset);if(item.thumbnail){const pic=paths.get(prefix+item.thumbnail);if(pic&&pic.type.startsWith('image/'))asset.thumbnail='data:'+pic.type+';base64,'+C.nativeAssets.encode64(await pic.arrayBuffer());}loaded.push(asset);}await C.nativeAssets.prepare(loaded);this.library=loaded;this.$('#library-message').textContent=`已获授权加载 ${loaded.length} 件本地模型。选择家具再点款式可替换；未选择则放入下拉房间。`;this.renderLibrary();}
  renderLibrary(){const $=this.$,list=$('#library-items');if(!list)return;list.replaceChildren();const query=$('#library-search').value.toLowerCase(),max=+$('#library-max-width').value||Infinity;for(const r of this.library.filter(r=>(r.name+' '+r.category+' '+(r.styles||[]).join(' ')).toLowerCase().includes(query)&&r.size[0]<=max)){const b=document.createElement('button');b.className='library-item';if(r.thumbnail){const img=document.createElement('img');img.src=r.thumbnail;b.append(img);}const name=document.createElement('b');name.textContent=r.name;const dims=document.createElement('small');dims.textContent=r.size.map(x=>x.toFixed(2)).join(' × ')+' m · '+(r.deform||'uniform');b.append(name,dims);b.onclick=()=>this.safe(()=>this.place(r));list.append(b);}}
  async place(r){const p=C.exportLayout(false),e=C.entities.find(e=>e.id===C.editor.selected&&e.type==='furniture'),old=e&&p.placements.find(x=>x.id===e.id);let placement;if(old){if(old.componentId!==r.componentId)throw Error('只允许同类替换；先取消选择可作为新家具放置');placement=old;placement.size=[...r.size];delete placement.materialOverrides;}else{const room=p.rooms.find(r=>r.id===this.$('#library-room').value);if(!room)throw Error('先选放置房间');const point=C.rooms.find(x=>x.id===room.id).point;placement={id:'asset-'+T.MathUtils.generateUUID().slice(0,8),name:r.name,roomId:room.id,componentId:r.componentId,position:[point[0],0,point[2]],size:[...r.size],rotationY:0};p.placements.push(placement);}placement.nativeAssetId=r.id;placement.name=r.name;(p.nativeAssets||=[]);if(!p.nativeAssets.some(a=>a.id===r.id))p.nativeAssets.push(structuredClone(r));const check=Spatial.audit(p,placement.id);if(check.errors.length||check.warnings.length){this.api.toast('保留待调整草稿：'+[...check.errors,...check.warnings].join(', '));p.source.assumptions.push('家具 '+placement.id+' 的放置观察：'+[...check.errors,...check.warnings].join(', ')+'；回源调整布局/选型，不自动隐藏或缩放。');}await this.api.apply(p);C.editor.setTab('furniture');C.editor.select(placement.id);this.refresh();this.selectedChanged();}
  async material(){const id=C.editor.selected,p=C.exportLayout(false),x=p.placements.find(x=>x.id===id);if(!x)throw Error('先选家具');const name=this.$('#native-slot').value,roughness=+this.$('#slot-roughness').value,metalness=+this.$('#slot-metalness').value;if(!name||![roughness,metalness].every(v=>v>=0&&v<=1))throw Error('无效材质槽参数');(x.materialOverrides||={})[name]={color:this.$('#slot-color').value,roughness,metalness};await this.api.apply(p);C.editor.select(id);this.selectedChanged();}
  async remove(){const p=C.exportLayout(false),id=C.editor.selected;if(!p.placements.some(x=>x.id===id))throw Error('先选家具');p.placements=p.placements.filter(x=>x.id!==id);p.rooms.forEach(r=>r.subjectIds=r.subjectIds.filter(x=>x!==id));p.lighting?.lights.forEach(l=>{if(l.anchorId===id)l.anchorId=null;});await this.api.apply(p);this.refresh();}
  downloadJSON(obj,name){C.downloadBlob(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),name);}
  saveHTML(){this.safe(async()=>{const snapshot=C.editor.exportProject(),layout=snapshot.layout,used=new Set(layout.placements.map(p=>p.nativeAssetId).filter(Boolean));layout.nativeAssets=(layout.nativeAssets||[]).filter(x=>used.has(x.id));layout.customStyle=structuredClone(C.activeStyle);const encode=x=>JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029'),d=new DOMParser().parseFromString(C.templateHTML,'text/html');d.querySelector('#project-json').textContent=encode(layout);d.querySelector('#saved-project')?.remove();const script=d.createElement('script');script.id='saved-project';script.type='application/json';script.textContent=encode(snapshot);d.body.prepend(script);const html='<!doctype html>\n'+d.documentElement.outerHTML;C.downloadBlob(new Blob([html],{type:'text/html'}),'interior-edited-complete.html');this.api.toast('完整HTML已保存，使用的GLB/贴图、布局、光源与机位均已内嵌。');});}
 };
})(window.CREAM,window.THREE);
